In [3]:
import pandas as pd
import os

In [4]:
reference_df = pd.read_csv('../region_status.csv')

In [8]:
#get mapping of region -> [Win, Lose, Swing]
mapping = reference_df.set_index('region')['status']
mapping = reference_df.drop_duplicates(subset='region').set_index('region')['status']
mapping

region
CHANTHABURI                 Lose
CHIANGRAI                   Lose
CHUMPHON                     Win
HAT YAI                     Lose
KANCHANABURI               Swing
KHONKAEN                    Lose
KRABI                        Win
LAMPANG                    Swing
NAKHONNAYOK                  Win
NAKHONPATHOM                Lose
NAKHONSAWAN                 Lose
NAKHONSRITHAMMARAT         Swing
NONGKHAI                   Swing
PHAYAO                     Swing
PHETCHABURI_Chaam          Swing
PRACHINBURI                Swing
RATCHABURI_Banpong         Swing
SAKAEO_Aranyaprathet         Win
SAKONNAKHON                  Win
SARABURI_Nongkhae            Win
SARABURI_Phraphutthabat      Win
SISAKET                      Win
SONGKHLA_City               Lose
SURATTHANI_City             Lose
SURIN                      Swing
TAK_Maesot                 Swing
TRAT                         Win
UDONTHANI                   Lose
UTTARADIT                   Lose
YASOTHON                     Win
Name: status, dtype: object

In [ ]:
folder_path_1 = '../progress_metrics/results'
folder_path_2 = '../progress_metrics/daily_guarantee/daily_guarantee_results'
folder_path_3 = '../mainexperiment/weekly/tier_merged'

output_path_1 = '../progress_metrics/results_updated'
output_path_2 = '../progress_metrics/daily_guarantee/daily_guarantee_results_updated'
output_path_3 = '../mainexperiment/weekly/tier_merged_updated'

In [15]:
#add to all incentives datasets
for filename in os.listdir(folder_path_1): 
    if filename.endswith('.csv'):
        df = pd.read_csv(os.path.join(folder_path_1, filename)) 
        df['status'] = df['region'].map(mapping) 
        # df = df.drop(['Unnamed: 0'], axis =1)
        df.to_csv(os.path.join(output_path_1, filename), index=False)

KeyError: 'region'

In [ ]:
pd.set_option('display.max_columns', None)

In [25]:
incentives_updated = pd.read_csv('../progress_metrics/results_updated/incentive_progress.csv')
incentives_updated.head()

,Region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Tier,Incentive,daily_order_count,time_per_order_sec,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,day_of_week,day_of_week_short,week_start_date,year,week,days_worked_count,days_worked_list,has_required_days,is_target1_day,is_target2_day,is_target3_day,orders_target1_cumulative,orders_target2_cumulative,orders_target3_cumulative,worked_target1_days,worked_target2_days,worked_target3_days,Daily Guarantee Required Online Hour,Daily Guarantee Hunting hour period,Daily Guarantee Required Hunting Hour,Daily Guarantee amount,Active Hour Required Online Hour,Active Hour Hunting hour period,Active Hour Required Hunting Hour,Active Hour Required day,Active Hour Require Dow,Active Hour Reward,Daily Productivity target,Daily Productivity Reward,Streak target,Streak Reward,streak target P1,streak reward P1,streak target P2,streak reward P2,streak target P3,streak reward P3,Start Date,End Date,days_required_worked_count,progress,Status
0,SURIN,LMD00BZBZ,2025-07-14 18:09:26.890,ซัซกูว ชาบูวากิว บุฟเฟต์ (Sasgoo Shabu Wagyu B...,Sukiyaki/Shabu,LMF-250714-380442187,True,19.80,3.0,129.0,4657.0,1763.1,1557,357,27,861,2802,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,Streak,1,888,888.0,888.0,888.0,0.246667,0.246667,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,1,0,0,False,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,1,0.011111,Swing
1,SURIN,LMD00BZBZ,2025-07-14 18:12:10.263,ผัดไทยสะบัดเส้น (Patthausabutsent) หลังมอ,Rice Dish,LMF-250714-460422944,True,17.00,3.0,111.8,3507.0,1882.8,1031,461,60,414,1966,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,Streak,2,474,1362.0,474.0,1362.0,0.378333,0.378333,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,2,0,0,False,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,1,0.022222,Swing
2,SURIN,LMD00BZBZ,2025-07-14 18:43:50.165,"หมูกรอบบอกต่อ (Crispy Pork, Spread the Word)",Street Food/Food Stands,LMF-250714-270459334,True,14.93,3.0,80.0,4379.0,214.9,1142,550,12,547,2251,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,Streak,3,559,1921.0,559.0,1921.0,0.533611,0.533611,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,3,0,0,False,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,1,0.033333,Swing
3,SURIN,LMD00BZBZ,2025-07-14 18:55:45.210,ผัดไทยหอยทอดแม่ทองตลาดไอคิว (Pad Thai Mea Thon...,Thai,LMF-250714-678571326,True,18.47,3.0,124.0,5455.0,2515.9,426,455,660,225,1766,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,Streak,4,885,2806.0,885.0,2806.0,0.779444,0.779444,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,4,0,0,False,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,1,0.044444,Swing
4,SURIN,LMD00BZBZ,2025-07-14 19:19:20.788,รอยยิ้มที่หายไป หลังบิ๊กซี,À La Carte,LMF-250714-345482995,True,21.40,3.0,77.4,5115.0,385.5,860,19,109,615,1603,COMPLETED,2025-07-14,SURIN,0.76,Light,Mid,Streak,5,724,3530.0,724.0,3530.0,0.980556,0.980556,Monday,Mon,2025-07-14,2025,29,1,Mon,False,True,False,False,5,0,0,False,False,False,7.0,6.0,5.0,995.0,7.0,6.0,5.0,6.0,"Mon, Fri, Sat, Sun",2395.0,31.0,400.0,30.0,2790.0,30.0,720.0,29.0,1200.0,32.0,880.0,2025-07-14,2025-07-20,1,0.055556,Swing

In [26]:
incentives_updated['Region'].unique()

array(['SURIN', 'UDONTHANI', 'NAKHONNAYOK', 'KHONKAEN', 'NONGKHAI',
       'UTTARADIT', 'TRAT', 'HAT YAI', 'RATCHABURI_Banpong', 'TAK_Maesot',
       'YASOTHON', 'CHIANGRAI', 'NAKHONPATHOM', 'KRABI', 'KANCHANABURI',
       'NAKHONSRITHAMMARAT', 'SURATTHANI_City', 'SISAKET', 'CHUMPHON',
       'SAKONNAKHON', 'CHANTHABURI', 'PRACHINBURI', 'SONGKHLA_City',
       'SARABURI_Nongkhae', 'SAKAEO_Aranyaprathet', 'PHAYAO',
       'NAKHONSAWAN', 'LAMPANG', 'PHETCHABURI_Chaam', 'PATTANI',
       'SARABURI_Phraphutthabat', 'BKK', 'NONGKHAI_Thabo',
       'CHIANGRAI_Maesai', 'PATTAYA', 'KORAT_CITY', 'SURATTHANI_Kosamui',
       'PHUKET', 'NAKHONPHANOM', 'PRACHINBURI_Simahaphot', 'SUPHANBURI',
       'KHONKAEN_Banphai', 'AMNATCHAROEN', 'NAKHONSRITHAMMARAT_Thasala',
       'AYUTTHAYA_Sena', 'UBONRATCHATHANI',
       'NAKHONSRITHAMMARAT_Thungsong', 'NONGBUALAMPHU'], dtype=object)

In [27]:
incentives_updated[incentives_updated['Region'] == 'PRACHINBURI_Simahaphot']

,Region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Tier,Incentive,daily_order_count,time_per_order_sec,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,day_of_week,day_of_week_short,week_start_date,year,week,days_worked_count,days_worked_list,has_required_days,is_target1_day,is_target2_day,is_target3_day,orders_target1_cumulative,orders_target2_cumulative,orders_target3_cumulative,worked_target1_days,worked_target2_days,worked_target3_days,Daily Guarantee Required Online Hour,Daily Guarantee Hunting hour period,Daily Guarantee Required Hunting Hour,Daily Guarantee amount,Active Hour Required Online Hour,Active Hour Hunting hour period,Active Hour Required Hunting Hour,Active Hour Required day,Active Hour Require Dow,Active Hour Reward,Daily Productivity target,Daily Productivity Reward,Streak target,Streak Reward,streak target P1,streak reward P1,streak target P2,streak reward P2,streak target P3,streak reward P3,Start Date,End Date,days_required_worked_count,progress,Status
996315,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 07:56:19.333,ร้านข้าวเเกง เจ๊สม (-ร้านข้าวเเกง เจ๊สม) บ้านเ...,Thai,LMF-250810-794116148,True,25.96,0.0,120.0,6543.0,415.2,529,516,1720,329,3094,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,1,2049,2049.0,0.0,0.0,0.569167,0.000000,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,4,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996316,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 08:02:46.083,ข้าวมันไก่ไชยยา (Chaiya Chicken Rice),Rice Dish,LMF-250810-956418309,True,20.38,0.0,163.0,4715.0,646.5,4,329,1502,319,2154,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,2,1821,3870.0,0.0,0.0,1.075000,0.000000,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,5,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996317,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 08:03:32.264,Café Amazon - SC3498 (คาเฟ่ อเมซอน - SC3498) S...,Café/Coffee Shop,LMF-250810-742316384,True,18.21,0.0,60.0,3004.0,1947.9,2,1782,375,35,2194,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,3,410,4280.0,0.0,0.0,1.188889,0.000000,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,6,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996318,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 09:40:12.641,ภัท-ทิ-ดา กาแฟสด (Phat-Thi-Da Fresh Coffee),Café/Coffee Shop,LMF-250810-382769376,True,25.00,0.0,51.0,3661.0,1001.5,1023,464,19,764,2270,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,4,783,5063.0,0.0,0.0,1.406389,0.000000,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,7,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996319,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 15:10:34.169,ก๋วยเตี๋ยวเรือทองแพร304 (Golden Boat Noodles 3...,Noodles,LMF-250810-635098113,True,19.69,0.0,85.0,5142.0,773.2,300,213,637,212,1362,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,5,849,5912.0,0.0,0.0,1.642222,0.000000,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,8,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996320,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 15:14:40.369,ร้านผลไม้หน้าเซเว่นบ้านเอื้อ (Fruit Shop in Fr...,Street Food/Food Stands,LMF-250810-394547320,True,16.59,0.0,189.0,2743.0,413.5,1115,371,38,436,1960,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,6,474,6386.0,0.0,0.0,1.773889,0.000000,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,9,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996321,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 15:29:32.990,ส้มตำเดอนัว (Som Tum De Nua),North East,LMF-250810-998438681,True,17.50,0.0,52.0,3154.0,214.3,720,360,702,19,1801,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,7,721,7107.0,0.0,0.0,1.974167,0.000000,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,10,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996322,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 15:33:32.204,เมี่ยงปลาเผาอบโอ่ง(โป่งไผ่) (Clay Pot Grilled ...,North East,LMF-250810-318635999,True,17.50,0.0,177.0,2988.0,166.3,483,403,353,272,1511,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,8,625,7732.0,0.0,0.0,2.147778,0.000000,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,11,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996323,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 16:58:07.565,Coco Walk นิคม 304 ปราจีนบุรี (Coco Walk Nikom...,Juice/Coffee/Tea/Soft drinks,LMF-250810-326643929,True,20.90,0.0,250.6,1483.0,770.3,1027,1127,172,777,3103,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,9,949,8681.0,0.0,0.0,2.411389,0.000000,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,12,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996324,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 17:12:17.220,ร้านคุณหญิง8หนึ่ง (แยกท่าตูม ซอยโรงเรียนสอนขับ...,Thai,LMF-250810-289191712,True,20.90,0.0,79.0,3412.0,1715.4,728,749,788,1163,3428,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,10,1951,10632.0,1951.0,1951.0,2.953333,0.541944,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,13,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996325,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 18:53:05.331,CHA LUM DEE byคุณนัท (ชาลำดี) สาขาโปร่งไผ่,Café/Coffee Shop,LMF-250810-971030390,True,17.71,0.0,69.0,2243.0,1548.9,720,425,705,433,2283,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,11,1138,11770.0,1138.0,3089.0,3.269444,0.858056,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,14,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996326,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 19:05:02.209,ซามูไรอาหารจานเดียว (Samurai Single Dish),À La Carte,LMF-250810-752362096,True,17.72,0.0,110.0,2778.0,1269.0,23,759,6,358,1146,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,12,364,12134.0,364.0,3453.0,3.370556,0.959167,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,15,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996327,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 19:25:57.764,กะเพราถาด & ก๋วยเตี๋ยวไก่ (Tray Krapow & Chick...,À La Carte,LMF-250810-008950172,True,22.60,0.0,210.0,5153.0,595.7,1288,1562,25,1443,4318,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,13,1468,13602.0,1468.0,4921.0,3.778333,1.366944,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,16,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
996328,PRACHINBURI_Simahaphot,LMDC1EVZX,2025-08-10 19:35:42.050,ครัวเถื่อน (Wild Kitchen),À La Carte,LMF-250810-459477205,True,23.88,0.0,115.0,5555.0,107.8,428,573,1469,366,2836,COMPLETED,2025-08-10,NaN,NaN,NaN,NaN,NaN,14,1835,15437.0,1835.0,6756.0,4.288056,1.876667,Sunday,Sun,2025-08-04,2025,32,7,"Fri, Mon, Sat, Sun, Thu, Tue, Wed",True,False,False,True,19,54,17,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN

In [28]:
incentives_updated[incentives_updated['Region'] == 'NAKHONSRITHAMMARAT_Thasala']

,Region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Tier,Incentive,daily_order_count,time_per_order_sec,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,day_of_week,day_of_week_short,week_start_date,year,week,days_worked_count,days_worked_list,has_required_days,is_target1_day,is_target2_day,is_target3_day,orders_target1_cumulative,orders_target2_cumulative,orders_target3_cumulative,worked_target1_days,worked_target2_days,worked_target3_days,Daily Guarantee Required Online Hour,Daily Guarantee Hunting hour period,Daily Guarantee Required Hunting Hour,Daily Guarantee amount,Active Hour Required Online Hour,Active Hour Hunting hour period,Active Hour Required Hunting Hour,Active Hour Required day,Active Hour Require Dow,Active Hour Reward,Daily Productivity target,Daily Productivity Reward,Streak target,Streak Reward,streak target P1,streak reward P1,streak target P2,streak reward P2,streak target P3,streak reward P3,Start Date,End Date,days_required_worked_count,progress,Status
1924088,NAKHONSRITHAMMARAT_Thasala,LMDN3KEXH,2025-08-02 15:15:05.320,ข้าวไก่ กุ๊ก กุ๊ก เซเว่นหน้ามอ,Rice Dish,LMF-250802-709934209,True,28.00,0.0,168.00,4985.0,2682.2,83,507,257,392,1239,COMPLETED,2025-08-02,NAKHONSRITHAMMARAT_Thasala,0.0,no-rain,NaN,NaN,1,649,649.0,0.0,0.0,0.180278,0.000000,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,1,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1924089,NAKHONSRITHAMMARAT_Thasala,LMDN3KEXH,2025-08-02 15:27:27.518,นุช ส้มตำริมทาง ร้อยเอ็ด (Nut somtum Rimtang R...,North East,LMF-250802-062864280,True,19.69,5.0,124.00,4660.0,1872.9,765,421,8,497,1691,COMPLETED,2025-08-02,NAKHONSRITHAMMARAT_Thasala,0.0,no-rain,NaN,NaN,2,505,1154.0,0.0,0.0,0.320556,0.000000,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,2,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1924090,NAKHONSRITHAMMARAT_Thasala,LMDN3KEXH,2025-08-02 15:28:48.106,นุช ส้มตำริมทาง ร้อยเอ็ด (Nut somtum Rimtang R...,North East,LMF-250802-667680409,True,20.88,5.0,124.00,5058.0,0.0,810,291,512,97,1710,COMPLETED,2025-08-02,NAKHONSRITHAMMARAT_Thasala,0.0,no-rain,NaN,NaN,3,609,1763.0,0.0,0.0,0.489722,0.000000,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,3,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1924091,NAKHONSRITHAMMARAT_Thasala,LMDN3KEXH,2025-08-02 15:35:48.884,ข้าวไก่ กุ๊ก กุ๊ก เซเว่นหน้ามอ,Rice Dish,LMF-250802-911979259,True,22.63,0.0,52.00,5709.0,1389.3,254,119,950,247,1570,COMPLETED,2025-08-02,NAKHONSRITHAMMARAT_Thasala,0.0,no-rain,NaN,NaN,4,1197,2960.0,0.0,0.0,0.822222,0.000000,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,4,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1924092,NAKHONSRITHAMMARAT_Thasala,LMDN3KEXH,2025-08-02 15:58:52.473,ตำยำอเวจี 29 บาท,North East,LMF-250802-186051033,True,14.00,5.0,74.00,1995.0,3535.5,750,2054,651,507,3962,COMPLETED,2025-08-02,NAKHONSRITHAMMARAT_Thasala,0.0,no-rain,NaN,NaN,5,1158,4118.0,0.0,0.0,1.143889,0.000000,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,5,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1924161,NAKHONSRITHAMMARAT_Thasala,LMDN3KEXH,2025-08-08 17:56:32.675,ฟาฟู่ปังน้ำเต้าหู้เยาวราช ฟาฟู่ปังน้ำเต้าหู้เย...,Thai,LMF-250808-955218758,True,25.22,0.0,170.00,6902.0,706.0,255,283,1185,62,1785,COMPLETED,2025-08-08,NAKHONSRITHAMMARAT_Thasala,0.0,no-rain,NaN,NaN,5,1247,3624.0,1247.0,2324.0,1.006667,0.645556,Friday,Fri,2025-08-04,2025,32,3,"Fri, Mon, Tue",False,False,True,False,24,5,0,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1924162,NAKHONSRITHAMMARAT_Thasala,LMDN3KEXH,2025-08-08 18:37:37.139,ชวนเชยย อาหารตามสั่ง (Chuan Chuey Made-to-Orde...,Thai,LMF-250808-705227730,True,20.29,0.0,75.00,4043.0,121.2,375,995,303,378,2051,COMPLETED,2025-08-08,NAKHONSRITHAMMARAT_Thasala,0.0,no-rain,NaN,NaN,6,681,4305.0,681.0,3005.0,1.195833,0.834722,Friday,Fri,2025-08-04,2025,32,3,"Fri, Mon, Tue",False,False,True,False,24,6,0,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1924163,NAKHONSRITHAMMARAT_Thasala,LMDN3KEXH,2025-08-08 18:43:46.222,หอมหมี่ไก่ (Hom Mi Kai),Noodles,LMF-250808-170923644,True,16.91,0.0,100.00,1401.0,210.9,6,1090,6,195,1297,COMPLETED,2025-08-08,NAKHONSRITHAMMARAT_Thasala,0.0,no-rain,NaN,NaN,7,201,4506.0,201.0,3206.0,1.251667,0.890556,Friday,Fri,2025-08-04,2025,32,3,"Fri, Mon, Tue",False,False,True,False,24,7,0,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1924164,NAKHONSRITHAMMARAT_Thasala,LMDN3KEXH,2025-08-08 18:49:16.775,ครัวกินดี 99,À La Carte,LMF-250808-748131170,True,27.30,0.0,50.00,5799.0,1908.2,1060,441,1330,173,3004,COMPLETED,2025-08-08,NAKHONSRITHAMMARAT_Thasala,0.0,no-rain,NaN,NaN,8,1503,6009.0,1503.0,4709.0,1.669167,1.308056,Friday,Fri,2025-08-04,2025,32,3,"Fri, Mon, Tue",False,False,True,False,24,8,0,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
1924165,NAKHONSRITHAMMARAT_Thasala,LMDN3KEXH,2025-08-08 18:51:13.686,หมูกรอบคำโต,Rice Dish,LMF-250808-716768995,True,17.50,0.0,76.54,2584.0,3355.9,965,936,6,819,2726,COMPLETED,2025-08-08,NAKHONSRITHAMMARAT_Thasala,0.0,no-rain,NaN,NaN,9,825,6834.0,825.0,5534.0,1.898333,1.537222,Friday,Fri,2025-08-04,2025,32,3,"Fri, Mon, Tue",False,False,True,False,24,9,0,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN

In [29]:
incentives_updated[incentives_updated['Region'] == 'UBONRATCHATHANI']

,Region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Tier,Incentive,daily_order_count,time_per_order_sec,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,day_of_week,day_of_week_short,week_start_date,year,week,days_worked_count,days_worked_list,has_required_days,is_target1_day,is_target2_day,is_target3_day,orders_target1_cumulative,orders_target2_cumulative,orders_target3_cumulative,worked_target1_days,worked_target2_days,worked_target3_days,Daily Guarantee Required Online Hour,Daily Guarantee Hunting hour period,Daily Guarantee Required Hunting Hour,Daily Guarantee amount,Active Hour Required Online Hour,Active Hour Hunting hour period,Active Hour Required Hunting Hour,Active Hour Required day,Active Hour Require Dow,Active Hour Reward,Daily Productivity target,Daily Productivity Reward,Streak target,Streak Reward,streak target P1,streak reward P1,streak target P2,streak reward P2,streak target P3,streak reward P3,Start Date,End Date,days_required_worked_count,progress,Status
2220444,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 08:55:24.643,ร้านลาบหน้าลือ (Lab Na Lue Restaurant),North East,LMF-250803-250384179,True,27.00,2.0,200.00,4776.0,3449.6,662,891,380,510,2443,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,1,890,890.0,0.0,0.0,0.247222,0.000000,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,1,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220445,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 09:15:52.767,KFC (เคเอฟซี) โลตัส วารินชำราบ,Fastfood,LMF-250803-426062701,True,27.00,2.0,369.00,4210.0,2508.8,708,1125,213,177,2223,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,2,390,1280.0,0.0,0.0,0.355556,0.000000,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,2,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220446,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 10:14:15.212,Forest Cafe,Café/Coffee Shop,LMF-250803-983412360,True,27.00,2.0,116.48,4559.0,927.1,496,731,356,604,2187,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,3,960,2240.0,960.0,960.0,0.622222,0.266667,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,3,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220447,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 10:22:25.595,HOP Chafe ฮ็อป ชาเฟ วารินชำราบ (HOP Chafe Wari...,Bubble Milk Tea,LMF-250803-738143256,True,23.51,2.0,116.00,5452.8,33.8,1102,200,1488,713,3503,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,4,2201,4441.0,2201.0,3161.0,1.233611,0.878056,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,4,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220448,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 11:11:25.539,ภรณ์อาหารตามสั่ง (Porn's Made to Order Food) -,À La Carte,LMF-250803-674427805,True,20.73,2.0,70.00,3443.0,1400.8,600,201,1319,229,2349,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,5,1548,5989.0,1548.0,4709.0,1.663611,1.308056,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,5,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220449,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 11:22:00.029,ข้าวมันไก่หน้าบ้าน,Thai,LMF-250803-868402947,True,20.73,2.0,81.40,2202.0,5.7,6,856,426,185,1473,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,6,611,6600.0,611.0,5320.0,1.833333,1.477778,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,6,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220450,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 11:28:51.328,อาหารตามสั่งอุ๋มอิ๋ม,À La Carte,LMF-250803-410118408,True,20.74,2.0,75.00,2109.0,1150.0,5,52,433,297,787,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,7,730,7330.0,730.0,6050.0,2.036111,1.680556,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,7,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220451,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 11:52:26.169,ไก่ย่างวิเชียรบุรีเจ้ออ บ้านห้วยไผ่,North East,LMF-250803-321183298,True,34.20,2.0,195.00,6774.0,2087.4,5,1862,55,378,2300,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,8,433,7763.0,433.0,6483.0,2.156389,1.800833,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,8,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220452,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 12:27:46.349,ดีดี ซูชิ วารินชำราบ (DD Sushi Warinchamrab),Sushi,LMF-250803-146773278,True,25.70,2.0,97.90,4770.0,3143.5,634,548,671,290,2143,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,9,961,8724.0,961.0,7444.0,2.423333,2.067778,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,9,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220453,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 12:36:17.543,ก๋วยเตี๋ยวมิตรสัมพันธ์ (Friendship Noodle) อุบ...,Noodles,LMF-250803-957446396,True,25.70,2.0,110.00,3421.0,4153.6,624,673,348,350,1995,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,10,698,9422.0,698.0,8142.0,2.617222,2.261667,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,10,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220454,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 13:06:30.335,WRToys&Cafe อุบลราชธานี,Café/Coffee Shop,LMF-250803-401068173,True,20.70,2.0,125.00,3426.0,1304.8,1792,630,709,540,3671,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,11,1249,10671.0,0.0,8142.0,2.964167,2.261667,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,11,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220455,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 13:06:30.387,The 28 Coffee Toast&Bistro,Café/Coffee Shop,LMF-250803-626526013,True,20.70,2.0,60.00,924.0,1516.6,1501,916,41,385,2843,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,12,426,11097.0,0.0,8142.0,3.082500,2.261667,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,12,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220456,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 13:31:51.818,หมวยเล็กใจดี (Mouy Lek Jai Dee),À La Carte,LMF-250803-619075627,True,20.50,2.0,119.00,4155.0,3137.5,424,425,460,515,1824,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,13,975,12072.0,0.0,8142.0,3.353333,2.261667,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,13,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220457,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 13:35:11.152,แอ๊บขายอาหารตามสั่ง (อุปถัมภ์ซอย9) (Aep Order ...,Rice Dish,LMF-250803-860051187,True,32.20,2.0,69.37,6273.0,792.2,1820,124,6,548,2498,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,14,554,12626.0,0.0,8142.0,3.507222,2.261667,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,14,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220458,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 13:38:52.310,ราดหน้าอ่างทอง (RAT NA ANG THONG RESTAURANT),Noodles,LMF-250803-510063771,True,20.50,2.0,50.00,3098.0,1750.4,94,833,589,154,1670,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,15,743,13369.0,0.0,8142.0,3.713611,2.261667,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,15,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2220459,UBONRATCHATHANI,LMDQRE8ZA,2025-08-03 15:10:01.687,Mixue (มี่เสวี่ย) ตลาดวาริน,Ice Cream,LMF-250803-925485006,True,27.00,2.0,86.00,4455.0,478.8,604,534,104,397,1639,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,16,501,13870.0,0.0,8142.0,3.852778,2.261667,Sunday,Sun,2025-07-28,2025,31,1,Sun,False,False,False,True,0,0,16,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756891,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 06:28:00.045,ร้านโจ้กเมืองทอง สุขาอุปถัมป์ (Joke Muang Thon...,Breakfast/Brunch,LMF-250802-340708715,True,27.00,2.0,60.00,1120.0,1313.5,11,614,87,318,1030,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,1,405,405.0,0.0,0.0,0.112500,0.000000,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,1,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756892,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 06:48:23.753,Café Amazon - DD2750 (คาเฟ่ อเมซอน - DD2750) อ...,Café/Coffee Shop,LMF-250802-629570083,True,27.00,2.0,120.00,884.0,1557.8,608,183,25,351,1167,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,2,376,781.0,0.0,0.0,0.216944,0.000000,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,2,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756893,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 07:16:39.221,หมูทอดชัยภูมิ - บิ๊กซีอุบล (Fried Pork Chaiya...,À La Carte,LMF-250802-142753044,True,28.81,2.0,60.00,8409.0,486.5,352,973,837,11,2173,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,3,848,1629.0,0.0,0.0,0.452500,0.000000,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,3,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756894,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 07:22:21.416,Café Amazon - SD4765 (คาเฟ่ อเมซอน - SD4765) m...,Café/Coffee Shop,LMF-250802-344751747,True,31.59,2.0,55.00,9109.0,1639.5,9,225,753,823,1810,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,4,1576,3205.0,0.0,0.0,0.890278,0.000000,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,4,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756895,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 07:51:23.375,ปุ้มข้าวเหนียวหมูฝอยหมูสวรรค์ (Poom Sticky Ric...,Thai,LMF-250802-749675306,True,27.00,2.0,49.00,1158.0,765.6,609,189,423,203,1424,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,5,626,3831.0,0.0,0.0,1.064167,0.000000,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,5,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756896,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 09:53:24.351,ร้านลาบกกยางใหญ่ (Lab Kok Yang Yai Shop),North East,LMF-250802-518125696,True,27.00,2.0,130.00,3632.0,513.5,603,677,18,416,1714,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,6,434,4265.0,0.0,0.0,1.184722,0.000000,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,6,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756897,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 10:22:54.211,กะเพรา มหาโจร (Basil Maha Jon) ถนน คลังอาวุธ,À La Carte,LMF-250802-884171889,True,27.80,2.0,144.00,5158.0,432.3,648,431,17,477,1573,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,7,494,4759.0,494.0,494.0,1.321944,0.137222,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,7,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756898,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 11:36:50.201,Bonchon Korean Fried Chicken (บอนชอนไก่ทอดเกาห...,Korean,LMF-250802-914241317,True,30.20,2.0,338.00,5807.0,2556.9,15,985,55,1211,2266,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,8,1266,6025.0,1266.0,1760.0,1.673611,0.488889,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,8,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756899,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 12:25:47.785,ไก่ย่างวิเชียรบุรี. ลาบแซ่บ (ร้านไก่ย่างวิเชีย...,North East,LMF-250802-297376758,True,20.50,2.0,159.00,2284.0,1632.4,457,449,236,216,1358,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,9,452,6477.0,452.0,2212.0,1.799167,0.614444,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,9,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756900,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 12:28:19.597,Café Amazon - SD4509 (คาเฟ่ อเมซอน - SD4509) ห...,Café/Coffee Shop,LMF-250802-243362650,True,20.50,2.0,215.00,1361.0,1770.9,305,650,267,301,1523,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,10,568,7045.0,568.0,2780.0,1.956944,0.772222,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,10,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756901,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 12:40:52.395,ร้านส้มตำอารีย์(หน้าสุขศาลาบ้านดู่) (Ari Papay...,North East,LMF-250802-315236837,True,27.00,2.0,88.00,4795.0,502.3,612,287,25,568,1492,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,11,593,7638.0,593.0,3373.0,2.121667,0.936944,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,11,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756902,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 15:02:31.410,DEK-CHA เด็กชา สาขาอุบลฯ (DEK-CHA Ubon Branch),Bubble Milk Tea,LMF-250802-644807978,True,22.50,2.0,95.00,1488.0,3824.5,393,1758,169,232,2552,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,12,401,8039.0,0.0,3373.0,2.233056,0.936944,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,12,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756903,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 15:08:54.945,Potato Corner (โปเตโต้ คอร์เนอร์) Central Ubon...,Fastfood,LMF-250802-388772510,True,22.50,2.0,298.00,4079.0,2774.1,10,622,1148,139,1919,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,13,1287,9326.0,0.0,3373.0,2.590556,0.936944,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,13,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756904,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 15:53:48.235,หมี่ไก่ฉีก YUMMY อุบล,Noodles,LMF-250802-972458230,True,20.50,2.0,65.00,677.0,754.7,641,248,296,302,1487,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,14,598,9924.0,0.0,3373.0,2.756667,0.936944,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,14,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756905,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 16:01:10.391,มิสเตอร์ปัณณ์ เมี่ยงปลาหมุน (Mr.Pun Mueng Pla ...,North East,LMF-250802-451865539,True,20.50,2.0,65.00,1316.0,1407.9,184,533,318,337,1372,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,15,655,10579.0,0.0,3373.0,2.938611,0.936944,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,15,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756906,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 16:55:50.746,แชมป์ อาหารตามสั่ง เปิด 24 ชม. (Champion Made...,À La Carte,LMF-250802-999756240,True,20.50,2.0,88.00,2957.0,275.6,606,255,729,311,1901,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,16,1040,11619.0,0.0,3373.0,3.227500,0.936944,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,16,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756907,UBONRATCHATHANI,LMDWXR3O4,2025-08-02 17:08:13.986,Café Amazon - SD5102 (คาเฟ่ อเมซอน - SD5102) ต...,Café/Coffee Shop,LMF-250802-579715888,True,20.50,2.0,115.00,1171.0,659.5,6,256,285,276,823,COMPLETED,2025-08-02,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,17,561,12180.0,561.0,3934.0,3.383333,1.092778,Saturday,Sat,2025-07-28,2025,31,1,Sat,False,False,False,True,0,0,17,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756908,UBONRATCHATHANI,LMDWXR3O4,2025-08-03 06:01:14.994,ร้านโจ้กเมืองทอง สุขาอุปถัมป์ (Joke Muang Thon...,Breakfast/Brunch,LMF-250803-417526801,True,23.95,2.0,60.00,1120.0,1313.0,607,875,116,188,1786,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,1,304,304.0,0.0,0.0,0.084444,0.000000,Sunday,Sun,2025-07-28,2025,31,2,"Sat, Sun",False,False,False,True,0,0,18,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756909,UBONRATCHATHANI,LMDWXR3O4,2025-08-03 06:15:06.533,ร้านโจ้กเมืองทอง สุขาอุปถัมป์ (Joke Muang Thon...,Breakfast/Brunch,LMF-250803-232351035,True,24.65,2.0,63.20,5181.0,0.0,10,640,317,723,1690,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,2,1040,1344.0,0.0,0.0,0.373333,0.000000,Sunday,Sun,2025-07-28,2025,31,2,"Sat, Sun",False,False,False,True,0,0,19,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756910,UBONRATCHATHANI,LMDWXR3O4,2025-08-03 06:42:12.183,แชมป์ อาหารตามสั่ง เปิด 24 ชม. (Champion Made...,À La Carte,LMF-250803-594713074,True,27.00,2.0,236.00,842.0,439.9,599,425,29,222,1275,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,3,251,1595.0,0.0,0.0,0.443056,0.000000,Sunday,Sun,2025-07-28,2025,31,2,"Sat, Sun",False,False,False,True,0,0,20,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756911,UBONRATCHATHANI,LMDWXR3O4,2025-08-03 07:23:51.121,"สามชัยกาแฟสาขาดอนกลาง (Samchai Coffee, Don Kla...",Breakfast/Brunch,LMF-250803-959247911,True,20.50,2.0,150.00,4212.0,1430.3,140,285,290,345,1060,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,4,635,2230.0,0.0,0.0,0.619444,0.000000,Sunday,Sun,2025-07-28,2025,31,2,"Sat, Sun",False,False,False,True,0,0,21,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756912,UBONRATCHATHANI,LMDWXR3O4,2025-08-03 07:24:27.364,Café Amazon - DD737 (คาเฟ่ อเมซอน - DD737) บจ....,Café/Coffee Shop,LMF-250803-258480751,True,20.50,2.0,75.00,2903.0,1529.3,103,546,390,5,1044,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,5,395,2625.0,0.0,0.0,0.729167,0.000000,Sunday,Sun,2025-07-28,2025,31,2,"Sat, Sun",False,False,False,True,0,0,22,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
2756913,UBONRATCHATHANI,LMDWXR3O4,2025-08-03 07:55:59.681,น้องไอเท็มกระเพราสามแยก,À La Carte,LMF-250803-764539942,True,27.00,2.0,90.00,4218.0,1297.2,601,434,28,468,1531,COMPLETED,2025-08-03,UBONRATCHATHANI,0.0,no-rain,NaN,NaN,6,496,3121.0,0.0,0.0,0.866944,0.000000,Sunday,Sun,2025-07-28,2025,31,2,"Sat, Sun",False,False,False,True,0,0,23,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN

In [30]:
#add to all incentives datasets
for filename in os.listdir(folder_path_2): 
    if filename.endswith('.csv'):
        df = pd.read_csv(os.path.join(folder_path_2, filename)) 
        df['Status'] = df['region'].map(mapping) 
        df = df.drop(['Unnamed: 0'], axis =1)
        df.to_csv(os.path.join(output_path_2, filename), index=False)

In [ ]:
week1_updated = pd.read_csv('../progress_metrics/daily_guarantee/daily_guarantee_results_updated/daily_guarantee_daily_productivity_tiers_merged_0714-0716.csv')
week1_updated

,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date,Incentive,daily_order_count,time_per_order_sec,time_worked_sec,hour,daily_cumulative_time_sec,time_worked_in_window_sec,window_cumulative_sec,daily_cumulative_time_hr,window_cumulative_hr,Status
0,SURATTHANI_City,LMD0INE39,2025-07-14 00:00:09.002,ก๋วยเตี๋ยวแชมป์ ตลาดศรีราชา- ถนนศรีวิชัย (Cham...,Noodles,LMF-250714-779356509,True,14.34,0.0,120.00,3901.0,862.5,6,102,517,275,900,COMPLETED,2025-07-14,SURATTHANI_City,1.150,Light,Bottom,2025-07-14,2025-07-20,Guarantee,1,792,792,0,792,0,0,0.220000,0.000000,Lose
1,SAKONNAKHON,LMDBLGUGP,2025-07-14 00:00:19.057,เว้าพื้นตำ (ลี้แซ่บ3 ลานหน้าตะวันแดง),North East,LMF-250714-209383660,True,12.28,2.0,145.34,3596.0,1977.3,75,449,1110,152,1786,COMPLETED,2025-07-14,SAKONNAKHON,7.490,Moderate,Mid,2025-07-14,2025-07-20,Streak,1,1262,1262,0,1262,0,0,0.350556,0.000000,Win
2,CHIANGRAI,LMDJ32RYY,2025-07-14 00:00:22.445,Apple coffee food (แอปเปิ้ล กาแฟ ฟู้ด),Juice/Coffee/Tea/Soft drinks,LMF-250714-231817500,False,23.00,0.0,153.00,757.0,2169.4,0,0,0,0,0,EXPIRED,2025-07-14,CHIANGRAI,4.860,Light,Mid,2025-07-14,2025-07-20,No Incentive,0,0,0,0,0,0,0,0.000000,0.000000,Lose
3,SURIN,LMDMZJYNR,2025-07-14 00:00:28.170,ไฉไลนมสด (Chai Lai Fresh Milk),Juice/Coffee/Tea/Soft drinks,LMF-250714-268976661,True,19.76,3.0,262.00,5684.0,2584.0,416,671,2114,296,3497,COMPLETED,2025-07-14,SURIN,0.760,Light,Top,2025-07-14,2025-07-20,Streak,1,2410,2410,0,2410,0,0,0.669444,0.000000,Swing
4,HAT YAI,LMDPBNV24,2025-07-14 00:00:32.011,โรตีนูซี (ROTI NUZY) โต้รุ่งพลาซ่า หาดใหญ่ (Ro...,Dessert,LMF-250714-739732847,True,18.70,0.0,60.00,4044.0,1330.4,6,496,647,264,1413,COMPLETED,2025-07-14,NaN,NaN,NaN,Top,2025-07-14,2025-07-20,Active Bonus,1,911,911,0,911,0,0,0.253056,0.000000,Lose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305159,UDONTHANI,LMD8RHR4Z,2025-07-16 23:59:23.186,ก้อยบ้านห้วย (Koi Ban Huai),North East,LMF-250716-765947132,True,24.00,0.0,224.00,3497.0,2743.9,67,716,8,562,1353,COMPLETED,2025-07-16,UDONTHANI,0.000,no-rain,Top,2025-07-14,2025-07-20,Daily Productivity,25,570,570,23,22365,0,6557,6.212500,1.821389,Lose
305160,CHIANGRAI,LMDK6CYM4,2025-07-16 23:59:35.117,กินเล่น,Fastfood,LMF-250716-876487596,False,33.40,3.0,137.00,7379.0,4734.6,0,0,0,0,0,EXPIRED,2025-07-16,CHIANGRAI,0.182,Light,Mid,2025-07-14,2025-07-20,No Incentive,39,0,0,23,29251,0,10015,8.125278,2.781944,Lose
305161,CHIANGRAI,LMD0XS04P,2025-07-16 23:59:59.312,ตำยำริมรั้ว ห้าแยก,North East,LMF-250716-340312927,False,41.20,0.0,64.00,8715.0,538.5,21,1032,156,1682,2891,COMPLETED,2025-07-16,CHIANGRAI,0.182,Light,Top,2025-07-14,2025-07-20,No Incentive,15,1838,0,23,15315,0,4916,4.254167,1.365556,Lose
305162,CHIANGRAI,LMD41D4M6,2025-07-16 23:59:59.312,ตำยำริมรั้ว ห้าแยก,North East,LMF-250716-340312927,True,41.20,0.0,64.00,8715.0,538.5,21,1032,156,1682,2891,COMPLETED,2025-07-16,CHIANGRAI,0.182,Light,Mid,2025-07-14,2025-07-20,No Incentive,8,1838,1838,23,5782,0,0,1.606111,0.000000,Lose
305163,SONGKHLA_City,LMDE1Y5CZ,2025-07-17 00:10:16.923,Mixue (มี่เสวี่ย) วชิรา สงขลา,Ice Cream,LMF-250716-063992948,True,22.00,0.0,43.00,508.0,794.6,1794,377,129,112,2412,COMPLETED,2025-07-17,NaN,NaN,NaN,Mid,2025-07-14,2025-07-20,Daily Productivity,1,241,241,0,241,0,0,0.066944,0.000000,Lose

In [32]:
week1_updated['region'].unique()

array(['SURATTHANI_City', 'SAKONNAKHON', 'CHIANGRAI', 'SURIN', 'HAT YAI',
       'KHONKAEN', 'UDONTHANI', 'TRAT', 'NAKHONSRITHAMMARAT',
       'CHANTHABURI', 'NAKHONPATHOM', 'SONGKHLA_City', 'PRACHINBURI',
       'PHETCHABURI_Chaam', 'NAKHONSAWAN', 'SISAKET', 'LAMPANG', 'KRABI',
       'KANCHANABURI', 'CHUMPHON', 'SAKAEO_Aranyaprathet', 'NONGKHAI',
       'PATTAYA', 'SARABURI_Phraphutthabat', 'TAK_Maesot',
       'SARABURI_Nongkhae', 'RATCHABURI_Banpong', 'YASOTHON',
       'NAKHONNAYOK', 'PHAYAO', 'NAKHONSRITHAMMARAT_Thungsong',
       'UTTARADIT', 'SUPHANBURI', 'PATTANI', 'PHUKET', 'UBONRATCHATHANI',
       'SURATTHANI_Kosamui', 'PHETCHABURI', 'AYUTTHAYA_Sena',
       'NARATHIWAT', 'NAKHONSRITHAMMARAT_Thasala', 'CHIANG_MAI',
       'MAHASARAKHAM', 'KORAT_CITY', 'TRANG', 'RATCHABURI',
       'KHONKAEN_Banphai', 'NAKHONPHANOM'], dtype=object)

In [33]:
week1_updated.columns

Index(['region', 'driver_id', 'assign_created_at', 'restaurant_name',
       'restaurant_category', 'order_id', 'is_driver_accept', 'wage',
       'on_top_fare', 'basket_size', 'drop_off_distance',
       'distance_rider_to_restaurant', 'placed_to_match_second',
       'rider_matched_to_arrived_restaurant_second',
       'rider_waiting_time_in_restaurant_second',
       'delivery_time_to_user_second', 'total_user_waiting_time_second',
       'order_status', 'date', 'region::multi-filter', 'avg_rain',
       'Rain_Level', 'Rider Group', 'Start Date', 'End Date', 'Incentive',
       'daily_order_count', 'time_per_order_sec', 'time_worked_sec', 'hour',
       'daily_cumulative_time_sec', 'time_worked_in_window_sec',
       'window_cumulative_sec', 'daily_cumulative_time_hr',
       'window_cumulative_hr', 'Status'],
      dtype='object')