In [2]:
import pandas as pd

In [ ]:
rider_log = pd.read_csv('./mainexperiment/riderperf-0710-0803.csv')

In [3]:
rider_log.head(4)

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,...,active_driver_offpeak,aa_completed,zone_online_day,region_online_day,region_active_day,total_income,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost,"prod_hour_'food','mart','messenger','bike'"
0,2025-07-14,KHONKAEN,N,LMDZI7TCW,5,Mueang Khon Kaen,994745720,BRONZE,NaN,8.9773,...,1,18,1.0,1.0,1.0,400.32,0.0,0.0,0.0,0.0
1,2025-07-30,PHETCHABURI_Chaam,N,LMD0QWPPE,9,Cha-Am,616126526,LEGEND,NaN,11.2984,...,1,0,1.0,1.0,1.0,661.50,0.0,0.0,0.0,0.0
2,2025-07-20,CHIANGRAI,N,LMD9KT8TQ,1,Mueang Chiang Rai,893860076,BRONZE,NaN,4.5170,...,1,0,1.0,1.0,1.0,331.60,0.0,0.0,0.0,0.0
3,2025-07-20,KANCHANABURI,N,LMD0WTV92,3,Mueang Kanchanaburi,861611838,BRONZE,NaN,3.0068,...,1,0,1.0,1.0,1.0,102.00,0.0,0.0,0.0,0.0

In [4]:
rider_log.columns

Index(['date', 'region', 'zone', 'driver_id', 'rider_level',
       'most_freq_district', 'phone', 'driver_tier', 'dedicated_zones',
       'total_online_hour', 'peak_online_hour', 'offpeak_online_hour',
       'total_assign_hour', 'active_day', 'auto_assigned',
       'auto_assigned_food', 'auto_assigned_mart', 'auto_assigned_messenger',
       'auto_assigned_bike', 'auto_assigned_accepted',
       'auto_assigned_accepted_food', 'auto_assigned_accepted_mart',
       'auto_assigned_accepted_messenger', 'auto_assigned_accepted_bike',
       'completed', 'completed_peak', 'completed_offpeak', 'completed_food',
       'completed_mart', 'completed_messenger', 'completed_bike',
       'cancelled_free', 'cancelled_free_food', 'cancelled_free_mart',
       'cancelled_free_messenger', 'cancelled_free_bike', 'cancelled_not_free',
       'cancelled_not_free_food', 'cancelled_not_free_mart',
       'cancelled_not_free_messenger', 'cancelled_not_free_bike',
       'driver_wage_food', 'driver_wage_mart', 'driver_wage_msg',
       'driver_wage_bike', 'DELIVERY_FEE_DYNAMIC_ON_TOP',
       'DELIVERY_FEE_DYNAMIC_ON_TOP_food', 'DELIVERY_FEE_DYNAMIC_ON_TOP_mart',
       'DELIVERY_FEE_DYNAMIC_ON_TOP_msg', 'DELIVERY_FEE_DYNAMIC_ON_TOP_bike',
       'CONVERT_COIN_TO_CASH_'food','mart','messenger','bike'',
       'guarantee_'food','mart','messenger','bike'',
       'active_bonus_'food','mart','messenger','bike'',
       'streak_'food','mart','messenger','bike'',
       'period_'food','mart','messenger','bike'',
       'daily_'food','mart','messenger','bike'',
       'own_fleet_wage_'food','mart','messenger','bike'',
       'own_fleet_incentive_'food','mart','messenger','bike'',
       'CONVERT_VAULT_COINS_TO_CASH_'food','mart','messenger','bike'',
       'main_peak_hour_weekly_other_emg_incentive_no_id_'food','mart','messenger','bike'',
       'tier_productivity_incentive', 'active_driver', 'active_driver_peak',
       'active_driver_offpeak', 'aa_completed', 'zone_online_day',
       'region_online_day', 'region_active_day', 'total_income',
       'extra_non_wage_cost', 'peak_extra_non_wage_cost',
       'offpeak_extra_non_wage_cost',
       'prod_hour_'food','mart','messenger','bike''],
      dtype='object')

In [6]:
rider_log['rider_level'].unique()

array(['5', '9', '1', '3', '2', '8', '6', '4', '7', '0', '-'],
      dtype=object)

In [8]:
driver_demo = pd.read_csv('./mainexperiment/driverdemographics.csv')

In [9]:
driver_demo.head(5)

,driver_id,region,approved_date,status,approved_month,first_all_completed_order_date,first_service_type,first_mart_order_at,first_messenger_order_at,first_food_order_at,first_bike_order_at
0,LMDSEBPN7,BKK,2021-12-28,ASSIGNED,2021-12-01,2021-12-29,food,2022-01-03,2023-03-06,2021-12-29,2024-11-20
1,LMD4V10GS,SAKONNAKHON,2022-02-22,OFFLINE,2022-02-01,2022-02-24,food,2024-05-21,2023-04-11,2022-02-24,2025-03-04
2,LMDV0JXJU,BKK,2024-03-02,OFFLINE,2024-03-01,2024-03-17,messenger,2024-03-17,2024-03-17,2024-03-31,2024-03-26
3,LMDP9PCC0,BKK,2024-02-13,OFFLINE,2024-02-01,2024-02-15,bike,2024-02-16,2024-03-16,2024-09-05,2024-02-15
4,LMDNCDEUV,BKK,2024-03-08,OFFLINE,2024-03-01,2024-03-10,mart,2024-03-10,2024-03-10,2024-08-16,2024-03-10

In [10]:
pos = pd.read_excel('./mainexperiment/pos-0710-0829.xlsx')

In [11]:
pos.head(5)

,service_region::filter,province::multi-filter,district::multi-filter,segment::filter,order_dt,total_tx,branches,gmv_delivery_platforms,premium_gmv_delivery_platforms,lower_mass_gmv_delivery_platforms,...,premium_shopeefood_delivery_tx_share,lower_mass_shopeefood_delivery_tx_share,premium_lineman_delivery_tx_share,premium_grab_delivery_tx_share,lower_mass_lineman_delivery_tx_share,lower_mass_grab_delivery_tx_share,premium_lineman_delivery_gmv_share,premium_grab_delivery_gmv_share,lower_mass_lineman_delivery_gmv_share,lower_mass_grab_delivery_gmv_share
0,BKK,Bangkok,Dusit,All,2025-07-10,550,16,46387.51,25248.62,21138.89,...,0.030769,0.036810,0.646154,0.246154,0.760736,0.202454,0.557996,0.356455,0.771464,0.195989
1,PRACHINBURI_Simahaphot,ALL,ALL,All,2025-07-10,300,6,13623.39,4490.00,9133.39,...,0.076923,0.038462,0.846154,0.000000,0.846154,0.012821,0.657906,NaN,0.848249,0.017080
2,BKK,Bangkok,Ratchathewi,All,2025-07-10,3020,50,168491.80,107445.30,61046.50,...,0.030405,0.088937,0.246622,0.716216,0.327549,0.583514,0.245430,0.722265,0.304481,0.614597
3,BKK,Bangkok,Taling Chan,All,2025-07-10,3547,51,187876.11,139342.83,48533.28,...,0.027473,0.074246,0.260989,0.706044,0.292343,0.628770,0.257621,0.717354,0.356319,0.561180
4,UDONTHANI,ALL,ALL,All,2025-07-10,2085,41,61345.57,23650.85,37694.72,...,0.100000,0.315068,0.312500,0.587500,0.241096,0.443836,0.332794,0.579472,0.251670,0.456212

In [12]:
incentive_info = pd.read_csv('./rider_log.csv')

In [13]:
incentive_info.head(5)

,Input,Input.1,Input.2,Input.3,Input.4,Input.5,Input.6,Formula,Formula.1,Formula.2,Formula.3,Formula.4,Formula.5
0,Start Date,End Date,Rider List,Rider Group,Get Incentive,Incentive,Region,Cluster,Incentive Sequence,Column for Vertical Analysis,Column for Horizontal Rider Behavior,"Is Same Rider Between 1,2 / 3,4",Column for Vertical Rider Behavior
1,2025-07-10,2025-07-13,LMDX7OS7Y,Top,TRUE,Daily Productivity,SARABURI_Nongkhae,EXP - Win,Daily Productivity: First Recovery Week,Recovery Week,-,-,Recovery Week to Daily Productivity
2,2025-07-10,2025-07-13,LMDN1M7RY,Top,TRUE,Streak,NAKHONSAWAN,EXP - Lose,Streak: First Recovery Week,Recovery Week,-,-,Recovery Week to Streak
3,2025-07-10,2025-07-13,LMD456V1N,Top,TRUE,No Incentive,RATCHABURI_Banpong,EXP - Swing,No Incentive: First Recovery Week,Recovery Week,-,-,Recovery Week to No Incentive
4,2025-07-10,2025-07-13,LMDR2EJ9V,Top,TRUE,Daily Productivity,SISAKET,EXP - Win,Daily Productivity: First Recovery Week,Recovery Week,-,-,Recovery Week to Daily Productivity

In [14]:
weather = pd.read_csv('./mainexperiment/rain-0710-0829.csv')

In [15]:
weather.head(5)

  region::multi-filter        date  avg_rain Rain_Level
0         AMNATCHAROEN  2024-07-10      2.05      Light
1         AMNATCHAROEN  2024-07-11      0.20      Light
2         AMNATCHAROEN  2024-07-12      0.00    no-rain
3         AMNATCHAROEN  2024-07-13      0.00    no-rain
4         AMNATCHAROEN  2024-07-14      3.65      Light

In [18]:
weather.columns

Index(['region::multi-filter', 'date', 'avg_rain', 'Rain_Level'], dtype='object')

In [19]:
weather['region'] = weather['region::multi-filter']

In [20]:
merged_7_10 = pd.merge(
    rider_log, 
    weather,
    left_on=['date', 'region'],
    right_on=['date', 'region'],
    how='left' )

In [21]:
merged_7_10.head(5)

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,...,region_online_day,region_active_day,total_income,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost,"prod_hour_'food','mart','messenger','bike'",region::multi-filter,avg_rain,Rain_Level
0,2025-07-14,KHONKAEN,N,LMDZI7TCW,5,Mueang Khon Kaen,994745720,BRONZE,NaN,8.9773,...,1.0,1.0,400.32,0.0,0.0,0.0,0.0,KHONKAEN,1.78,Light
1,2025-07-30,PHETCHABURI_Chaam,N,LMD0QWPPE,9,Cha-Am,616126526,LEGEND,NaN,11.2984,...,1.0,1.0,661.50,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,2025-07-20,CHIANGRAI,N,LMD9KT8TQ,1,Mueang Chiang Rai,893860076,BRONZE,NaN,4.5170,...,1.0,1.0,331.60,0.0,0.0,0.0,0.0,CHIANGRAI,0.00,no-rain
3,2025-07-20,KANCHANABURI,N,LMD0WTV92,3,Mueang Kanchanaburi,861611838,BRONZE,NaN,3.0068,...,1.0,1.0,102.00,0.0,0.0,0.0,0.0,KANCHANABURI,0.00,no-rain
4,2025-07-18,YASOTHON,N,LMDAEEHPU,2,Mueang Yasothon,849956862,BRONZE,NaN,3.3652,...,1.0,1.0,70.00,0.0,0.0,0.0,0.0,YASOTHON,0.32,Light

In [3]:
july10 = pd.read_csv('./orderlevel_updated/tier_merged/tiers_merged_10-13 July.csv')

In [4]:
july10.head(15)

,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,...,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date
0,SURIN,LMD00BZBZ,2025-07-10 10:27:54.432,ก๋วยเตี๋ยวถนอมมิตร2 (Thanommit Noodles 2),Noodles,LMF-250710-408959062,True,13.50,3.0,30.0,...,249,687,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
1,SURIN,LMD00BZBZ,2025-07-10 10:32:29.887,ตำซี๊ด&อาหารตามสั่ง (Tum Zeed & Made-to-Order ...,Dessert,LMF-250710-161870697,True,17.80,3.0,95.0,...,385,1223,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
2,SURIN,LMD00BZBZ,2025-07-10 10:47:04.631,เฉิงกง ติ่มซำ (Chenggong Dim Sum) -,Dim Sum,LMF-250710-166811972,True,12.66,3.0,230.0,...,444,2458,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
3,SURIN,LMD00BZBZ,2025-07-10 10:56:22.791,Café Amazon - SD3192 (คาเฟ่ อเมซอน - SD3192) ส...,Café/Coffee Shop,LMF-250710-400808907,True,12.37,3.0,120.0,...,156,1180,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
4,SURIN,LMD00BZBZ,2025-07-10 11:09:04.244,Café Amazon - DD1655 (คาเฟ่ อเมซอน - DD1655) ป...,Café/Coffee Shop,LMF-250710-858627724,True,14.30,3.0,245.0,...,363,2035,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
5,SURIN,LMD00BZBZ,2025-07-10 11:11:38.237,Café Amazon - SD3192 (คาเฟ่ อเมซอน - SD3192) ส...,Café/Coffee Shop,LMF-250710-321972404,True,12.37,3.0,60.0,...,229,2253,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
6,SURIN,LMD00BZBZ,2025-07-10 11:23:47.869,Café Amazon - DD1655 (คาเฟ่ อเมซอน - DD1655) ป...,Café/Coffee Shop,LMF-250710-771935451,True,14.30,3.0,75.0,...,137,1297,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
7,SURIN,LMD00BZBZ,2025-07-10 11:33:30.396,PARLOR,Cafe,LMF-250710-015980523,True,11.40,3.0,464.0,...,235,2639,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
8,SURIN,LMD00BZBZ,2025-07-10 11:40:19.467,PunThai Coffee (กาแฟพันธุ์ไทย) ถนนหลักเมือง สุ...,Café/Coffee Shop,LMF-250710-466168679,True,11.40,3.0,137.0,...,413,2705,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
9,SURIN,LMD00BZBZ,2025-07-10 11:49:49.241,ลุงแหลมอาหารตามสั่งหน้าเทคนิค (Uncle Laem's Ma...,À La Carte,LMF-250710-422617314,True,11.40,3.0,155.0,...,143,1354,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
10,SURIN,LMD00BZBZ,2025-07-10 12:21:46.552,ส้มตำ ทบ.อุบลฯสาขาสุรินทร์ 2-เลียบคลอง,North East,LMF-250710-606162318,True,11.00,3.0,168.0,...,199,2334,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
11,SURIN,LMD00BZBZ,2025-07-10 12:25:36.115,ส้มตำ ทบ.อุบลฯสาขาสุรินทร์ 2-เลียบคลอง,North East,LMF-250710-932310469,True,11.00,3.0,71.0,...,292,1898,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
12,SURIN,LMD00BZBZ,2025-07-10 12:28:05.581,Café Amazon - SC1631 (คาเฟ่ อเมซอน - SC1631) โ...,Café/Coffee Shop,LMF-250710-063144884,True,11.00,3.0,365.0,...,145,1329,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
13,SURIN,LMD00BZBZ,2025-07-10 13:01:00.132,ลูกชิ้นทิพย์พี่นิต & ยำแซ่บ (Tip Meatballs P' ...,Street Food/Food Stands,LMF-250710-128251602,True,11.00,3.0,199.0,...,225,2001,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13
14,SURIN,LMD00BZBZ,2025-07-10 13:01:57.661,ตำแซ่บนัว - สาขาหลังมอ | By ยำแซ่บนัว ตำแซ่บนัว,North East,LMF-250710-104654016,True,17.00,3.0,123.0,...,426,942,COMPLETED,2025-07-10,SURIN,0.0,no-rain,Mid,2025-07-10,2025-07-13

In [6]:
july10_all = pd.read_csv('./mainexperiment/weekly/tier_merged/tiers_merged_all-0710-0713.csv')

In [7]:
july10_all.head(15)

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,...,total_income,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost,region::multi-filter,avg_rain,Rain_Level,Rider Group,Start Date,End Date
0,2025-07-10,NAKHONSAWAN,N,LMDF8Y0DZ,6,Mueang Nakhon Sawan,902367177,GOLD,NaN,5.5237,...,329.800000,0.0,0.0,0.0,NAKHONSAWAN,0.00,no-rain,Mid,2025-07-10,2025-07-13
1,2025-07-12,LAMPANG,N,LMDKXH3N0,8,Mueang Lampang,992713856,LEGEND,NaN,10.2829,...,1145.000000,0.0,0.0,0.0,LAMPANG,1.54,Light,Top,2025-07-10,2025-07-13
2,2025-07-10,SURIN,N,LMDGAIHHI,7,Mueang Surin,972357064,LEGEND,NaN,10.1746,...,982.600000,0.0,0.0,0.0,SURIN,0.00,no-rain,Mid,2025-07-10,2025-07-13
3,2025-07-10,SONGKHLA_City,N,LMDFQK4XV,8,Mueang Songkhla,928941259,LEGEND,NaN,9.5162,...,968.440000,0.0,0.0,0.0,NaN,NaN,NaN,Top,2025-07-10,2025-07-13
4,2025-07-11,SARABURI_Phraphutthabat,N,LMDXO0LPC,3,Phra Phutthabat,882324555,BRONZE,NaN,1.3522,...,125.020000,0.0,0.0,NaN,SARABURI_Phraphutthabat,0.00,no-rain,Bottom,2025-07-10,2025-07-13
5,2025-07-12,SARABURI_Nongkhae,N,LMDQ6VBIN,4,Nong Khae,819076347,BRONZE,NaN,5.1602,...,219.301963,0.0,0.0,0.0,SARABURI_Nongkhae,0.00,no-rain,Mid,2025-07-10,2025-07-13
6,2025-07-13,KHONKAEN,N,LMDCFJOY2,8,Mueang Khon Kaen,862513292,LEGEND,NaN,6.7501,...,566.280000,0.0,0.0,0.0,KHONKAEN,0.12,Light,Top,2025-07-10,2025-07-13
7,2025-07-11,KANCHANABURI,N,LMDQ8BHT6,6,Mueang Kanchanaburi,638989184,GOLD,NaN,10.1288,...,408.030000,0.0,0.0,0.0,KANCHANABURI,0.00,no-rain,Mid,2025-07-10,2025-07-13
8,2025-07-13,CHANTHABURI,N,LMDFZ4IZK,7,Mueang Chanthaburi,847826883,BRONZE,NaN,9.3929,...,1023.200000,0.0,0.0,0.0,CHANTHABURI,0.00,no-rain,Mid,2025-07-10,2025-07-13
9,2025-07-11,NAKHONSAWAN,N,LMDR3ME75,6,Mueang Nakhon Sawan,998786367,BRONZE,NaN,10.1650,...,620.000000,0.0,0.0,0.0,NAKHONSAWAN,0.00,no-rain,Mid,2025-07-10,2025-07-13
10,2025-07-12,UDONTHANI,N,LMDNITUZ9,1,Mueang Udon Thani,828026499,BRONZE,NaN,3.1294,...,74.000000,0.0,0.0,0.0,UDONTHANI,3.85,Light,Bottom,2025-07-10,2025-07-13
11,2025-07-11,KHONKAEN,N,LMDHNEAJF,7,Mueang Khon Kaen,642761908,MASTER,NaN,3.9589,...,349.760000,0.0,0.0,0.0,KHONKAEN,0.18,Light,Top,2025-07-10,2025-07-13
12,2025-07-10,SONGKHLA_City,N,LMD6KIJKW,9,Mueang Songkhla,804408218,LEGEND,NaN,17.4993,...,685.480000,0.0,0.0,0.0,NaN,NaN,NaN,Top,2025-07-10,2025-07-13
13,2025-07-13,SARABURI_Phraphutthabat,N,LMDHAJDZA,9,Phra Phutthabat,614918278,MASTER,NaN,14.5561,...,571.300000,0.0,0.0,0.0,SARABURI_Phraphutthabat,0.00,no-rain,Top,2025-07-10,2025-07-13
14,2025-07-11,SONGKHLA_City,N,LMDGXIF8J,9,Mueang Songkhla,958157491,LEGEND,NaN,14.6313,...,764.360000,0.0,0.0,0.0,NaN,NaN,NaN,Top,2025-07-10,2025-07-13