In [2]:
import pandas as pd

In [3]:
weather = pd.read_csv('./mainexperiment/rain-0710-0829.csv')

In [4]:
weather['region'] = weather['region::multi-filter']

In [5]:
from pathlib import Path
import os

In [11]:
# get all CSV files
csv_files = sorted(Path('./mainexperiment/weekly').glob('*.csv'))

# display all files
for i, file in enumerate(csv_files, 1):
    print(f"{i}. {file.name}")
    
# Process each file
for i, csv_file in enumerate(csv_files, 1):
    print(f"\n[{i}/{len(csv_files)}] Processing: {csv_file.name}")
    print("-" * 80)
    
    df = pd.read_csv(csv_file)
    df_merged = pd.merge(df, weather,
                on=['region', 'date'],
                how='left')

    output_name = f"merged_{csv_file.name}"
    output_path = os.path.join('./mainexperiment/weekly/weather_merged', output_name)
    
    # save to CSV
    df_merged.to_csv(output_path, index=False)

1. all-0710-0713.csv
2. all-0714-0720.csv
3. all-0721-0727.csv
4. all-0728-0810.csv
5. all-0811-0815.csv
6. all-0816-0822.csv
7. all-0823-0829.csv

[1/7] Processing: all-0710-0713.csv
--------------------------------------------------------------------------------

[2/7] Processing: all-0714-0720.csv
--------------------------------------------------------------------------------

[3/7] Processing: all-0721-0727.csv
--------------------------------------------------------------------------------

[4/7] Processing: all-0728-0810.csv
--------------------------------------------------------------------------------

[5/7] Processing: all-0811-0815.csv
--------------------------------------------------------------------------------

[6/7] Processing: all-0816-0822.csv
--------------------------------------------------------------------------------

[7/7] Processing: all-0823-0829.csv
--------------------------------------------------------------------------------

In [19]:
pd.read_csv('./mainexperiment/weekly/weather_merged/merged_all-0823-0829.csv')

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,...,region_online_day,region_active_day,total_income,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost,"prod_hour_'food','mart','messenger','bike'",region::multi-filter,avg_rain,Rain_Level
0,2025-08-23,HAT YAI,N,LMDK7UFYA,3,Hat Yai,818973145,BRONZE,NaN,6.4750,...,1,1,199.440000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN
1,2025-08-27,RATCHABURI_Banpong,N,LMDTD1UFZ,3,Ban Pong,954219040,BRONZE,NaN,10.4709,...,1,1,858.410000,0.000000,0.0,0.0,0.0,RATCHABURI_Banpong,0.000000,no-rain
2,2025-08-27,UDONTHANI,N,LMD4GYCT1,5,Mueang Udon Thani,829151323,GOLD,NaN,3.2016,...,1,1,173.280000,0.000000,0.0,0.0,0.0,UDONTHANI,8.638267,Moderate
3,2025-08-26,CHANTHABURI,N,LMDZT1HG5,9,Mueang Chanthaburi,892507653,GOLD,NaN,9.0885,...,1,1,404.570093,0.000000,0.0,0.0,0.0,CHANTHABURI,0.000000,no-rain
4,2025-08-28,NAKHONPATHOM,N,LMD5WQ9B4,1,Kamphaeng Saen,631690868,GOLD,NaN,5.5774,...,1,1,547.590000,0.000000,0.0,0.0,0.0,NAKHONPATHOM,0.000000,no-rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33686,2025-08-29,CHIANGRAI,N,LMDWBR0AI,5,Mueang Chiang Rai,864884840,GOLD,NaN,2.4037,...,1,1,286.800000,0.000000,0.0,0.0,0.0,CHIANGRAI,0.000000,no-rain
33687,2025-08-25,NAKHONSRITHAMMARAT,N,LMD7N77ZQ,4,Mueang Nakhon Si Thammarat,826569024,SILVER,NaN,3.0956,...,1,1,197.840000,0.000000,NaN,0.0,0.0,NAKHONSRITHAMMARAT,0.000000,no-rain
33688,2025-08-28,SAKONNAKHON,N,LMDSIB7G9,7,Mueang Sakon Nakhon,982043390,BRONZE,NaN,9.5167,...,1,1,285.275082,102.295082,0.0,0.0,0.0,SAKONNAKHON,0.000000,no-rain
33689,2025-08-27,NAKHONSAWAN,N,LMDANJ7BP,7,Mueang Nakhon Sawan,611376663,GOLD,NaN,4.5445,...,1,1,156.800000,0.000000,0.0,0.0,0.0,NAKHONSAWAN,0.000000,no-rain
33690,2025-08-29,SURIN,N,LMDQ8MWWB,-,Mueang Surin,807751235,BRONZE,NaN,3.9474,...,1,1,204.800000,0.000000,0.0,0.0,0.0,SURIN,2.160000,Light

In [27]:
weather.head(5)

  region::multi-filter        date  avg_rain Rain_Level        region
0         AMNATCHAROEN  2024-07-10      2.05      Light  AMNATCHAROEN
1         AMNATCHAROEN  2024-07-11      0.20      Light  AMNATCHAROEN
2         AMNATCHAROEN  2024-07-12      0.00    no-rain  AMNATCHAROEN
3         AMNATCHAROEN  2024-07-13      0.00    no-rain  AMNATCHAROEN
4         AMNATCHAROEN  2024-07-14      3.65      Light  AMNATCHAROEN

In [6]:
weather['date'] = pd.to_datetime(weather['date']).dt.date

In [ ]:
# get all CSV files
csv_files = sorted(Path('./orderlevel_updated').glob('*.csv'))

# display all files
for i, file in enumerate(csv_files, 1):
    print(f"{i}. {file.name}")
    
# Process each file
for i, csv_file in enumerate(csv_files, 1):
    print(f"\n[{i}/{len(csv_files)}] Processing: {csv_file.name}")
    print("-" * 80)
    
    df = pd.read_csv(csv_file)
    df['assign_created_at'] = pd.to_datetime(df['assign_created_at'])
    df['date'] = df['assign_created_at'].dt.date
    df_merged = pd.merge(df, weather,
                on=['region', 'date'],
                how='left')

    output_name = f"merged_{csv_file.name}"
    output_path = os.path.join('./orderlevel_updated/weather_merged', output_name)
    
    # save to CSV
    df_merged.to_csv(output_path, index=False)

1. 0710-0713.csv
2. 0714-0716.csv
3. 0717-0720.csv
4. 0721-0725.csv
5. 0726-0727.csv
6. 0728-0801.csv
7. 0802-0806.csv
8. 0807-0810.csv
9. 0811-0815.csv
10. 0816-0820.csv
11. 0821-0825.csv
12. 0826-0829.csv

[1/12] Processing: 0710-0713.csv
--------------------------------------------------------------------------------

[2/12] Processing: 0714-0716.csv
--------------------------------------------------------------------------------

[3/12] Processing: 0717-0720.csv
--------------------------------------------------------------------------------

[4/12] Processing: 0721-0725.csv
--------------------------------------------------------------------------------

[5/12] Processing: 0726-0727.csv
--------------------------------------------------------------------------------

[6/12] Processing: 0728-0801.csv
--------------------------------------------------------------------------------

[7/12] Processing: 0802-0806.csv
--------------------------------------------------------------------------------

[8/12] Processing: 0807-0810.csv
--------------------------------------------------------------------------------

[9/12] Processing: 0811-0815.csv
--------------------------------------------------------------------------------

[10/12] Processing: 0816-0820.csv
--------------------------------------------------------------------------------

[11/12] Processing: 0821-0825.csv
--------------------------------------------------------------------------------

[12/12] Processing: 0826-0829.csv
--------------------------------------------------------------------------------

In [34]:
pd.read_csv('./orderlevel/weather_merged/merged_10-13 July.csv')

,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,...,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,date,region::multi-filter,avg_rain,Rain_Level
0,SURIN,LMD00BZBZ,2025-07-10 10:27:54.432,ก๋วยเตี๋ยวถนอมมิตร2 (Thanommit Noodles 2),Noodles,LMF-250710-408959062,True,13.50,3.0,30.0,...,1,385,52,249,687,COMPLETED,2025-07-10,SURIN,0.00,no-rain
1,SURIN,LMD00BZBZ,2025-07-10 10:32:29.887,ตำซี๊ด&อาหารตามสั่ง (Tum Zeed & Made-to-Order ...,Dessert,LMF-250710-161870697,True,17.80,3.0,95.0,...,601,220,17,385,1223,COMPLETED,2025-07-10,SURIN,0.00,no-rain
2,SURIN,LMD00BZBZ,2025-07-10 10:47:04.631,เฉิงกง ติ่มซำ (Chenggong Dim Sum) -,Dim Sum,LMF-250710-166811972,True,12.66,3.0,230.0,...,666,261,1087,444,2458,COMPLETED,2025-07-10,SURIN,0.00,no-rain
3,SURIN,LMD00BZBZ,2025-07-10 10:56:22.791,Café Amazon - SD3192 (คาเฟ่ อเมซอน - SD3192) ส...,Café/Coffee Shop,LMF-250710-400808907,True,12.37,3.0,120.0,...,293,707,24,156,1180,COMPLETED,2025-07-10,SURIN,0.00,no-rain
4,SURIN,LMD00BZBZ,2025-07-10 11:09:04.244,Café Amazon - DD1655 (คาเฟ่ อเมซอน - DD1655) ป...,Café/Coffee Shop,LMF-250710-858627724,True,14.30,3.0,245.0,...,1177,228,267,363,2035,COMPLETED,2025-07-10,SURIN,0.00,no-rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488031,PHAYAO,LMDZZVYF8,2025-07-13 21:13:01.668,ลาบส้าต้มแซ่บ (Larb Sa Tom Zaap),North East,LMF-250713-669632413,True,15.00,0.0,244.0,...,62,1600,6,332,2000,COMPLETED,2025-07-13,PHAYAO,1.15,Light
488032,PHAYAO,LMDZZVYF8,2025-07-13 22:31:02.957,แก้วมณี 168 (Keawmanee 168),Noodles,LMF-250713-984272763,True,12.50,2.0,79.0,...,319,713,440,275,1747,COMPLETED,2025-07-13,PHAYAO,1.15,Light
488033,PHAYAO,LMDZZVYF8,2025-07-13 22:31:36.600,เฮียอู๊ดข้าวต้มโต้รุ่งพะเยา (Hia Ood Night Por...,Late Night Rice Porridge,LMF-250713-138478443,True,12.50,0.0,578.0,...,320,1102,794,319,2535,COMPLETED,2025-07-13,PHAYAO,1.15,Light
488034,PHAYAO,LMDZZVYF8,2025-07-13 22:41:57.267,ต้องปัง ไส้กรอก&ลูกชิ้นทอด ( เวียง ),Thai,LMF-250713-841635505,True,34.60,0.0,125.0,...,136,1983,7,573,2699,COMPLETED,2025-07-13,PHAYAO,1.15,Light
488035,PHAYAO,LMDZZVYF8,2025-07-13 23:40:35.562,กึ๊ดหม่ะออก (Can't Think of It),Street Food/Food Stands,LMF-250713-444585016,True,19.00,0.0,50.0,...,3,911,6,346,1266,COMPLETED,2025-07-13,PHAYAO,1.15,Light