In [8]:
import pandas as pd
import os
import glob

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
bkk_week1 = pd.read_csv('../bkk/bkk-0331-0427.csv')

In [5]:
bkk_week1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213412 entries, 0 to 213411
Data columns (total 65 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   date                              213412 non-null  object
 1   region                            213412 non-null  object
 2   zone                              213412 non-null  object
 3   driver_id                         213412 non-null  object
 4   rider_level                       213412 non-null  object
 5   most_freq_district                213390 non-null  object
 6   phone                             213412 non-null  int64
 7   driver_tier                       213412 non-null  object
 8   dedicated_zones                   42935 non-null   object
 9   total_online_hour                 213390 non-null  float64
 10  peak_online_hour                  197365 non-null  float64
 11  offpeak_online_hour               209272 non-null  float64
 12  total_assign_hour                 213390 non-null  float64
 13  active_day                        213412 non-null  int64
 14  auto_assigned                     213412 non-null  int64
 15  auto_assigned_food                213412 non-null  int64
 16  auto_assigned_mart                213412 non-null  int64
 17  auto_assigned_messenger           213412 non-null  int64
 18  auto_assigned_bike                213412 non-null  int64
 19  auto_assigned_accepted            213412 non-null  int64
 20  auto_assigned_accepted_food       213412 non-null  int64
 21  auto_assigned_accepted_mart       213412 non-null  int64
 22  auto_assigned_accepted_messenger  213412 non-null  int64
 23  auto_assigned_accepted_bike       213412 non-null  int64
 24  completed                         213412 non-null  int64
 25  completed_peak                    213412 non-null  int64
 26  completed_offpeak                 213412 non-null  int64
 27  completed_food                    213412 non-null  int64
 28  completed_mart                    213412 non-null  int64
 29  completed_messenger               213412 non-null  int64
 30  completed_bike                    213412 non-null  int64
 31  cancelled_free                    83503 non-null   float64
 32  cancelled_free_food               83503 non-null   float64
 33  cancelled_free_mart               83503 non-null   float64
 34  cancelled_free_messenger          83503 non-null   float64
 35  cancelled_free_bike               83503 non-null   float64
 36  cancelled_not_free                83503 non-null   float64
 37  cancelled_not_free_food           83503 non-null   float64
 38  cancelled_not_free_mart           83503 non-null   float64
 39  cancelled_not_free_messenger      83503 non-null   float64
 40  cancelled_not_free_bike           83503 non-null   float64
 41  driver_wage_food                  175843 non-null  float64
 42  driver_wage_mart                  128738 non-null  float64
 43  driver_wage_msg                   60292 non-null   float64
 44  driver_wage_bike                  33315 non-null   float64
 45  DELIVERY_FEE_DYNAMIC_ON_TOP       199766 non-null  float64
 46  DELIVERY_FEE_DYNAMIC_ON_TOP_food  175843 non-null  float64
 47  DELIVERY_FEE_DYNAMIC_ON_TOP_mart  128738 non-null  float64
 48  DELIVERY_FEE_DYNAMIC_ON_TOP_msg   58752 non-null   float64
 49  DELIVERY_FEE_DYNAMIC_ON_TOP_bike  28356 non-null   float64
 50  CONVERT_COIN_TO_CASH              109963 non-null  float64
 51  GUARANTEE                         11398 non-null   float64
 52  ACTIVE_BONUS                      18099 non-null   float64
 53  PRODUCTIVITY                      43463 non-null   float64
 54  total_income                      213412 non-null  float64
 55  extra_non_wage_cost               213412 non-null  float64
 56  peak_extra_non_wage_cost          197188 non-null  float64
 57  offpeak_extra_non_wage_cost       208902 non-null  float64
 58  active_driver                     213412 non-null  int64
 59  active_driver_peak                213412 non-null  int64
 60  active_driver_offpeak             213412 non-null  int64
 61  aa_completed                      213412 non-null  int64
 62  zone_online_day                   213390 non-null  float64
 63  region_online_day                 213390 non-null  float64
 64  region_active_day                 83503 non-null   float64
dtypes: float64(34), int64(23), object(8)
memory usage: 105.8+ MB

In [6]:
bkk_later_week = pd.read_csv('../bkk/bkk-0824-0826.csv')

In [7]:
bkk_later_week.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119447 entries, 0 to 119446
Data columns (total 18 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   region                                      119447 non-null  object
 1   driver_id                                   119447 non-null  object
 2   assign_created_at                           119447 non-null  object
 3   restaurant_name                             119447 non-null  object
 4   restaurant_category                         119447 non-null  object
 5   order_id                                    119447 non-null  object
 6   is_driver_accept                            119447 non-null  bool
 7   wage                                        119447 non-null  float64
 8   on_top_fare                                 119447 non-null  float64
 9   basket_size                                 119447 non-null  float64
 10  drop_off_distance                           119447 non-null  float64
 11  distance_rider_to_restaurant                119447 non-null  float64
 12  placed_to_match_second                      119447 non-null  int64
 13  rider_matched_to_arrived_restaurant_second  119447 non-null  int64
 14  rider_waiting_time_in_restaurant_second     119447 non-null  int64
 15  delivery_time_to_user_second                119447 non-null  int64
 16  total_user_waiting_time_second              119447 non-null  int64
 17  order_status                                119447 non-null  object
dtypes: bool(1), float64(5), int64(5), object(7)
memory usage: 15.6+ MB

In [9]:
incentives_mapping = {'guarantee_' : 'Daily Hours',
                      'active_bonus_' : 'Streak Hours', 
                      'streak_' : 'Streak Orders', 
                      'daily_': 'Daily Orders', 
                      'GUARANTEE': 'Daily Hours',
                      'ACTIVE_BONUS': 'Streak Hours', 
                      'PRODUCTIVITY': 'Daily Orders', #questionable...
                      }

In [28]:
def get_incentive(row):
    for col_key, incentive_val in incentives_mapping.items():
        matching_cols = [col for col in row.index if col_key in col]
        for col in matching_cols:
            if pd.notna(row[col]) and row[col] != '' and row[col] != 0:
                return incentive_val
    return None

In [29]:
folder_path = '../bkk'
output_folder = '../bkk_with_incentives'

In [30]:
os.makedirs(output_folder, exist_ok=True)

In [31]:
for filepath in glob.glob(os.path.join(folder_path, '*.csv')):  
    df = pd.read_csv(filepath) 

    df['incentive'] = df.apply(get_incentive, axis=1)

    file_name = os.path.basename(filepath)
    df.to_csv(os.path.join(output_folder, file_name), index=False)  
    print(f"Processed: {filepath}")

Processed: ../bkk/bkk-0824-0826.csv
Processed: ../bkk/bkk-1014.csv
Processed: ../bkk/bkk-0428-0525.csv
Processed: ../bkk/bkk-0526-0622.csv
Processed: ../bkk/bkk-1001.csv
Processed: ../bkk/bkk-1015.csv
Processed: ../bkk/bkk-1003.csv
Processed: ../bkk/bkk-1017.csv
Processed: ../bkk/bkk-1016.csv
Processed: ../bkk/bkk-1002.csv

/var/folders/s_/0td42yfs6wjd9wdpc5nr90400000gn/T/ipykernel_59591/2086365052.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filepath)

Processed: ../bkk/bkk-1001-1003.csv
Processed: ../bkk/bkk-1006.csv
Processed: ../bkk/bkk-1012.csv
Processed: ../bkk/bkk-1013.csv
Processed: ../bkk/bkk-1007.csv
Processed: ../bkk/bkk-1011.csv
Processed: ../bkk/bkk-1005.csv
Processed: ../bkk/bkk-1004.csv
Processed: ../bkk/bkk-1010.csv
Processed: ../bkk/bkk-1009.csv
Processed: ../bkk/bkk-1021.csv
Processed: ../bkk/bkk-1020.csv
Processed: ../bkk/bkk-1008.csv
Processed: ../bkk/bkk-1022.csv
Processed: ../bkk/bkk-0331-0427.csv
Processed: ../bkk/bkk-1023.csv
Processed: ../bkk/bkk-1024.csv
Processed: ../bkk/bkk-1018.csv
Processed: ../bkk/bkk-1004-1007.csv
Processed: ../bkk/bkk-1019.csv
Processed: ../bkk/bkk-0924-0926.csv

/var/folders/s_/0td42yfs6wjd9wdpc5nr90400000gn/T/ipykernel_59591/2086365052.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filepath)

Processed: ../bkk/bkk-1008-1010.csv

In [32]:
bkk_0331 = pd.read_csv('../bkk_with_incentives/bkk-0331-0427.csv')

In [35]:
bkk_0331

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,peak_online_hour,offpeak_online_hour,total_assign_hour,active_day,auto_assigned,auto_assigned_food,auto_assigned_mart,auto_assigned_messenger,auto_assigned_bike,auto_assigned_accepted,auto_assigned_accepted_food,auto_assigned_accepted_mart,auto_assigned_accepted_messenger,auto_assigned_accepted_bike,completed,completed_peak,completed_offpeak,completed_food,completed_mart,completed_messenger,completed_bike,cancelled_free,cancelled_free_food,cancelled_free_mart,cancelled_free_messenger,cancelled_free_bike,cancelled_not_free,cancelled_not_free_food,cancelled_not_free_mart,cancelled_not_free_messenger,cancelled_not_free_bike,driver_wage_food,driver_wage_mart,driver_wage_msg,driver_wage_bike,DELIVERY_FEE_DYNAMIC_ON_TOP,DELIVERY_FEE_DYNAMIC_ON_TOP_food,DELIVERY_FEE_DYNAMIC_ON_TOP_mart,DELIVERY_FEE_DYNAMIC_ON_TOP_msg,DELIVERY_FEE_DYNAMIC_ON_TOP_bike,CONVERT_COIN_TO_CASH,GUARANTEE,ACTIVE_BONUS,PRODUCTIVITY,total_income,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost,active_driver,active_driver_peak,active_driver_offpeak,aa_completed,zone_online_day,region_online_day,region_active_day,incentive
0,2025-03-31,BKK,N,LMDKAOPT7,-,Chatuchak,646784905,MEMBER,DBIKE_NORMAL_20052025,0.0000,NaN,0.0000,0.000000,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,NaN,NaN,0,0,0,0,1.0,1.0,0.0,NaN
1,2025-03-31,BKK,N,LMDQ5VEVE,8,Krathum Baen,939591240,PRO,NaN,44.2956,15.2437,29.0519,31.750302,7,213,193,7,13,0,138,133,0,5,0,138,52,86,133,0,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3943.61,NaN,465.158879,NaN,96.0,96.0,NaN,0.0,NaN,0.0,NaN,NaN,140.000000,4644.768879,0.0,0.0,0.0,1,1,1,0,7.0,7.0,NaN,Daily Orders
2,2025-04-07,BKK,N,LMDAWFHSI,1,Mueang Nonthaburi,985656963,SILVER,NaN,10.6552,2.9847,7.6706,5.816724,2,59,50,9,0,0,20,19,1,0,0,20,4,16,19,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,545.33,32.54,NaN,NaN,42.0,42.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,619.870000,0.0,0.0,0.0,1,1,1,0,4.0,4.0,NaN,NaN
3,2025-03-31,BKK,N,LMDATN6D2,8,Sai Mai,937450907,BASIC,NaN,57.7087,17.2233,40.4854,39.735982,7,733,689,42,0,2,152,146,6,0,0,149,57,92,144,5,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3774.16,190.32,NaN,NaN,431.0,424.0,7.0,NaN,NaN,0.0,NaN,NaN,NaN,4395.480000,0.0,0.0,0.0,1,1,1,0,7.0,7.0,NaN,NaN
4,2025-03-31,BKK,N,LMDQ1XMOY,9,Mueang Nonthaburi,812634129,PRO+,NaN,61.0347,27.3543,33.6806,56.398074,6,225,212,10,1,2,199,190,7,1,1,197,85,112,190,7,0,0,2.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,6182.65,260.08,85.000000,0.0,853.0,800.0,53.0,NaN,NaN,220.0,NaN,NaN,1144.051724,8744.781724,0.0,0.0,0.0,1,1,1,0,7.0,7.0,6.0,Daily Orders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213407,2025-03-31,BKK,N,LMDVI9YX4,2,Phutthamonthon,809824369,BASIC,NaN,13.2456,4.6916,8.5540,4.473504,4,60,58,2,0,0,21,20,1,0,0,21,5,16,20,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,521.03,30.00,NaN,NaN,24.0,19.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,575.030000,0.0,0.0,0.0,1,1,1,0,6.0,6.0,NaN,NaN
213408,2025-04-07,BKK,N,LMDH5TI1Y,8,Dusit,661357204,SILVER,NF_CBD_RED_ORG_PLUS_4,1.7052,1.7052,NaN,1.420536,2,8,8,0,0,0,7,7,0,0,0,7,7,0,7,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,181.50,NaN,NaN,NaN,55.0,55.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,236.500000,0.0,0.0,NaN,1,1,0,3,2.0,2.0,2.0,NaN
213409,2025-04-21,BKK,N,LMDSCHIIG,8,Mueang Pathum Thani,806842922,SILVER,NaN,31.8488,9.7154,22.1334,19.672073,6,125,116,9,0,0,91,88,3,0,0,91,38,53,88,3,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2621.83,108.76,NaN,NaN,48.0,48.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,2778.590000,0.0,0.0,0.0,1,1,1,0,6.0,6.0,2.0,NaN
213410,2025-04-07,BKK,N,LMD4A6JAV,1,Bang Bua Thong,972689732,SILVER,NaN,19.1949,7.4345,11.7604,6.754451,4,222,211,11,0,0,27,27,0,0,0,27,11,16,27,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,881.24,NaN,NaN,NaN,31.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,912.240000,0.0,0.0,0.0,1,1,1,0,4.0,4.0,NaN,NaN
213411,2025-03-31,BKK,N,LMDQXDHTM,3,Prawet,867625123,BASIC,NaN,13.5888,7.3348,6.2541,11.578232,6,56,46,10,0,0,49,41,8,0,0,49,33,16,41,8,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1143.88,210.18,NaN,NaN,190.0,163.0,27.0,NaN,NaN,0.0,NaN,NaN,NaN,1544.060000,0.0,0.0,0.0,1,1,1,0,6.0,6.0,NaN,NaN

In [42]:
bkk_0331[bkk_0331['incentive'] == 'Streak Hours']

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,peak_online_hour,offpeak_online_hour,total_assign_hour,active_day,auto_assigned,auto_assigned_food,auto_assigned_mart,auto_assigned_messenger,auto_assigned_bike,auto_assigned_accepted,auto_assigned_accepted_food,auto_assigned_accepted_mart,auto_assigned_accepted_messenger,auto_assigned_accepted_bike,completed,completed_peak,completed_offpeak,completed_food,completed_mart,completed_messenger,completed_bike,cancelled_free,cancelled_free_food,cancelled_free_mart,cancelled_free_messenger,cancelled_free_bike,cancelled_not_free,cancelled_not_free_food,cancelled_not_free_mart,cancelled_not_free_messenger,cancelled_not_free_bike,driver_wage_food,driver_wage_mart,driver_wage_msg,driver_wage_bike,DELIVERY_FEE_DYNAMIC_ON_TOP,DELIVERY_FEE_DYNAMIC_ON_TOP_food,DELIVERY_FEE_DYNAMIC_ON_TOP_mart,DELIVERY_FEE_DYNAMIC_ON_TOP_msg,DELIVERY_FEE_DYNAMIC_ON_TOP_bike,CONVERT_COIN_TO_CASH,GUARANTEE,ACTIVE_BONUS,PRODUCTIVITY,total_income,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost,active_driver,active_driver_peak,active_driver_offpeak,aa_completed,zone_online_day,region_online_day,region_active_day,incentive
5,2025-04-14,BKK,N,LMDHBKBA5,9,Mueang Samut Prakan,655803880,MASTER,NaN,76.7633,23.2054,53.5578,29.258188,7,99,98,1,0,0,92,91,1,0,0,89,18,71,88,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2902.18,25.43,NaN,NaN,77.0,77.0,0.0,NaN,NaN,0.0,NaN,2000.0,NaN,5004.610000,2000.0,0.0,0.0,1,1,1,0,7.0,7.0,NaN,Streak Hours
6,2025-04-14,BKK,N,LMDHWE1DJ,9,Bang Phli,642438476,MASTER,FOODBIKE_DRAGON_EMERALD,56.3737,20.1108,36.2629,31.552918,6,145,141,1,0,3,130,130,0,0,0,130,49,81,130,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4147.64,NaN,NaN,NaN,319.0,319.0,NaN,NaN,NaN,0.0,NaN,1750.0,1080.000000,7296.640000,1750.0,0.0,0.0,1,1,1,0,7.0,7.0,NaN,Streak Hours
21,2025-04-07,BKK,N,LMDECJFVK,9,Phra Samut Chedi,633589538,LEGEND,NaN,61.0506,17.5152,43.5355,25.244791,6,139,132,6,0,1,125,119,5,0,1,122,47,75,116,5,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3173.65,143.70,NaN,36.0,272.0,267.0,5.0,NaN,0.0,60.0,NaN,1800.0,460.000000,5945.350000,1800.0,0.0,0.0,1,1,1,0,6.0,6.0,NaN,Streak Hours
23,2025-04-07,BKK,N,LMD84Q83Q,8,Bang Phli,642072095,LEGEND,NaN,42.7905,14.3100,28.4805,27.995646,4,294,279,15,0,0,134,131,3,0,0,132,46,86,129,3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3739.96,100.29,NaN,NaN,516.0,514.0,2.0,NaN,NaN,NaN,NaN,1800.0,920.000000,7076.250000,1800.0,0.0,0.0,1,1,1,0,4.0,6.0,NaN,Streak Hours
63,2025-04-14,BKK,N,LMDF8RVTN,8,Bang Kruai,812933943,BRONZE,NaN,79.6877,26.8775,52.8103,43.503377,7,299,285,14,0,0,191,182,9,0,0,191,69,122,182,9,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4823.05,257.08,NaN,NaN,299.0,294.0,5.0,NaN,NaN,0.0,NaN,2000.0,360.000000,7739.130000,2000.0,0.0,0.0,1,1,1,84,7.0,7.0,NaN,Streak Hours
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213375,2025-04-14,BKK,N,LMD87VGJI,9,Mueang Samut Sakhon,626510574,LEGEND,NaN,52.3401,16.7757,35.5644,38.812023,5,171,169,2,0,0,171,169,2,0,0,170,55,115,168,2,0,0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5246.62,101.23,NaN,NaN,201.0,201.0,0.0,NaN,NaN,215.0,NaN,2000.0,1080.000000,8843.850000,2000.0,0.0,0.0,1,1,1,170,5.0,5.0,5.0,Streak Hours
213380,2025-03-31,BKK,N,LMDI9WLKA,9,Nong Khaem,612104275,PRO+,NaN,56.8190,22.7573,34.0618,44.584967,6,217,208,9,0,0,206,197,9,0,0,205,104,101,197,8,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5996.77,283.42,NaN,NaN,399.0,394.0,5.0,NaN,NaN,200.0,NaN,900.0,1018.542569,8797.732569,900.0,0.0,0.0,1,1,1,0,6.0,6.0,NaN,Streak Hours
213382,2025-04-07,BKK,N,LMDVKHVHA,6,Krathum Baen,886026149,SILVER,NaN,23.9087,11.6212,12.2875,9.653560,3,39,36,1,2,0,39,36,1,2,0,39,19,20,36,1,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1110.97,24.89,189.158879,NaN,86.0,86.0,0.0,0.0,NaN,NaN,NaN,950.0,NaN,2361.018879,950.0,0.0,0.0,1,1,1,39,3.0,3.0,NaN,Streak Hours
213400,2025-04-07,BKK,N,LMDFAW4HH,9,Krathum Baen,632011669,MASTER,NaN,68.9486,32.3410,36.6078,33.451671,7,125,123,2,0,0,125,123,2,0,0,124,65,59,122,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3854.83,101.25,NaN,NaN,231.0,226.0,5.0,NaN,NaN,0.0,NaN,1800.0,640.000000,6627.080000,1800.0,0.0,0.0,1,1,1,121,7.0,7.0,NaN,Streak Hours
213403,2025-03-31,BKK,N,LMDGJQ1AR,9,Mueang Samut Prakan,997802817,PRO,NaN,40.5963,16.7217,23.8746,25.634220,5,111,109,2,0,0,111,109,2,0,0,110,49,61,108,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3045.04,53.30,NaN,NaN,217.0,192.0,25.0,NaN,NaN,0.0,NaN,900.0,77.160494,4292.500494,900.0,0.0,0.0,1,1,1,110,5.0,5.0,NaN,Streak Hours

In [34]:
bkk_0331['incentive'].unique()

array([nan, 'Daily Orders', 'Streak Hours', 'Daily Hours'], dtype=object)

In [36]:
bkk_0924 = pd.read_csv('../bkk_with_incentives/bkk-0924-0926.csv')

In [37]:
bkk_0924

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,peak_online_hour,offpeak_online_hour,total_assign_hour,active_day,auto_assigned,auto_assigned_food,auto_assigned_mart,auto_assigned_messenger,auto_assigned_bike,auto_assigned_accepted,auto_assigned_accepted_food,auto_assigned_accepted_mart,auto_assigned_accepted_messenger,auto_assigned_accepted_bike,completed,completed_peak,completed_offpeak,completed_food,completed_mart,completed_messenger,completed_bike,cancelled_free,cancelled_free_food,cancelled_free_mart,cancelled_free_messenger,cancelled_free_bike,cancelled_not_free,cancelled_not_free_food,cancelled_not_free_mart,cancelled_not_free_messenger,cancelled_not_free_bike,driver_wage_food,driver_wage_mart,driver_wage_msg,driver_wage_bike,DELIVERY_FEE_DYNAMIC_ON_TOP,DELIVERY_FEE_DYNAMIC_ON_TOP_food,DELIVERY_FEE_DYNAMIC_ON_TOP_mart,DELIVERY_FEE_DYNAMIC_ON_TOP_msg,DELIVERY_FEE_DYNAMIC_ON_TOP_bike,"CONVERT_COIN_TO_CASH_'food','mart','messenger','bike'","guarantee_'food','mart','messenger','bike'","active_bonus_'food','mart','messenger','bike'","streak_'food','mart','messenger','bike'","period_'food','mart','messenger','bike'","daily_'food','mart','messenger','bike'","own_fleet_wage_'food','mart','messenger','bike'","own_fleet_incentive_'food','mart','messenger','bike'","CONVERT_VAULT_COINS_TO_CASH_'food','mart','messenger','bike'","main_peak_hour_weekly_other_emg_incentive_no_id_'food','mart','messenger','bike'",tier_productivity_incentive,active_driver,active_driver_peak,active_driver_offpeak,aa_completed,zone_online_day,region_online_day,region_active_day,total_income,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost,"prod_hour_'food','mart','messenger','bike'","gmv_'food','mart','messenger','bike'",incentive
0,2025-09-26,BKK,BKK - Swing,LMDSYSUQE,7,N,821453936,BRONZE,NaN,0.7554,0.7554,NaN,0.475636,1,4,4,0,0,0,3,3,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,46.14,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,0,1,1.0,1.0,1,48.140000,0.0,0.0,NaN,0.0,292.00,NaN
1,2025-09-24,BKK,BKK - Swing,LMDFRCJSX,4,N,929389659,BRONZE,NaN,9.0043,2.8481,6.1562,3.862327,1,394,383,11,0,0,24,24,0,0,0,24,7,17,24,0,0,0,0,0,0,0,0,0,0,0,0,0,688.80,NaN,NaN,NaN,95.0,95.0,NaN,NaN,NaN,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,783.800000,0.0,0.0,0.0,0.0,4958.97,NaN
2,2025-09-26,BKK,BKK - Win,LMDEFRJ8E,7,N,656966614,LEGEND,NaN,0.1667,NaN,0.1667,0.166667,1,1,1,0,0,0,1,1,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,40.36,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1.658291,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,0,1,0,1.0,1.0,1,42.018291,0.0,NaN,0.0,0.0,235.00,NaN
3,2025-09-26,BKK,BKK - Swing,LMDA68I72,7,N,876992597,LEGEND,NaN,7.9665,2.6953,5.2711,5.798721,1,24,24,0,0,0,24,24,0,0,0,24,7,17,24,0,0,0,0,0,0,0,0,0,0,0,0,0,747.76,NaN,NaN,NaN,17.0,17.0,NaN,NaN,NaN,55.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,819.760000,0.0,0.0,0.0,0.0,6823.23,NaN
4,2025-09-25,BKK,BKK - Swing,LMDI2SM2A,6,N,641468155,BRONZE,NaN,2.4714,2.0059,0.4656,1.914655,1,10,9,0,1,0,9,9,0,0,0,9,6,3,9,0,0,0,0,0,0,0,0,0,0,0,0,0,253.77,NaN,NaN,NaN,12.0,12.0,NaN,NaN,NaN,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,265.770000,0.0,0.0,0.0,0.0,1294.28,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5980,2025-09-26,BKK,BKK - Swing,LMD9GI3DJ,9,N,814748739,MASTER,NaN,4.0000,2.0000,2.0000,3.457361,1,17,14,2,1,0,17,14,2,1,0,17,7,10,14,2,1,0,0,0,0,0,0,0,0,0,0,0,408.29,59.17,144.448598,NaN,14.0,14.0,0.0,0.0,NaN,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,17,1.0,1.0,1,625.908598,0.0,0.0,0.0,0.0,3248.48,NaN
5981,2025-09-26,BKK,BKK - Swing,LMDWJAQR7,4,N,994261151,BRONZE,NaN,6.0926,1.8638,4.2290,3.727241,1,31,26,5,0,0,18,17,1,0,0,17,4,13,16,1,0,0,0,0,0,0,0,0,0,0,0,0,438.16,35.70,NaN,NaN,17.0,17.0,0.0,NaN,NaN,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,490.860000,0.0,0.0,0.0,0.0,2872.90,NaN
5982,2025-09-26,BKK,BKK - Swing,LMDZOIRGF,6,N,930537444,BRONZE,NaN,11.7036,3.9566,7.7470,7.640607,1,75,72,3,0,0,41,38,3,0,0,40,14,26,37,3,0,0,0,0,0,0,0,0,0,0,0,0,924.26,84.30,NaN,NaN,28.0,28.0,0.0,NaN,NaN,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,1036.560000,0.0,0.0,0.0,0.0,7569.36,NaN
5983,2025-09-25,BKK,BKK - Swing,LMD66ADBA,5,N,829580499,BRONZE,NaN,8.7797,2.4089,6.3708,3.291015,1,671,601,30,40,0,21,21,0,0,0,21,9,12,21,0,0,0,0,0,0,0,0,0,0,0,0,0,680.35,NaN,NaN,NaN,108.0,108.0,NaN,NaN,NaN,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,788.350000,0.0,0.0,0.0,0.0,3848.68,NaN
5984,2025-09-26,BKK,BKK - Lose,LMD66ADBA,5,N,829580499,BRONZE,NaN,NaN,NaN,NaN,NaN,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0,0,0,0,NaN,NaN,1,0.000000,0.0,NaN,NaN,0.0,0.00,NaN

In [40]:
bkk_0924[bkk_0924["streak_'food','mart','messenger','bike'"] != 0]

Empty DataFrame
Columns: [date, region, zone, driver_id, rider_level, most_freq_district, phone, driver_tier, dedicated_zones, total_online_hour, peak_online_hour, offpeak_online_hour, total_assign_hour, active_day, auto_assigned, auto_assigned_food, auto_assigned_mart, auto_assigned_messenger, auto_assigned_bike, auto_assigned_accepted, auto_assigned_accepted_food, auto_assigned_accepted_mart, auto_assigned_accepted_messenger, auto_assigned_accepted_bike, completed, completed_peak, completed_offpeak, completed_food, completed_mart, completed_messenger, completed_bike, cancelled_free, cancelled_free_food, cancelled_free_mart, cancelled_free_messenger, cancelled_free_bike, cancelled_not_free, cancelled_not_free_food, cancelled_not_free_mart, cancelled_not_free_messenger, cancelled_not_free_bike, driver_wage_food, driver_wage_mart, driver_wage_msg, driver_wage_bike, DELIVERY_FEE_DYNAMIC_ON_TOP, DELIVERY_FEE_DYNAMIC_ON_TOP_food, DELIVERY_FEE_DYNAMIC_ON_TOP_mart, DELIVERY_FEE_DYNAMIC_ON_TOP_msg, DELIVERY_FEE_DYNAMIC_ON_TOP_bike, CONVERT_COIN_TO_CASH_'food','mart','messenger','bike', guarantee_'food','mart','messenger','bike', active_bonus_'food','mart','messenger','bike', streak_'food','mart','messenger','bike', period_'food','mart','messenger','bike', daily_'food','mart','messenger','bike', own_fleet_wage_'food','mart','messenger','bike', own_fleet_incentive_'food','mart','messenger','bike', CONVERT_VAULT_COINS_TO_CASH_'food','mart','messenger','bike', main_peak_hour_weekly_other_emg_incentive_no_id_'food','mart','messenger','bike', tier_productivity_incentive, active_driver, active_driver_peak, active_driver_offpeak, aa_completed, zone_online_day, region_online_day, region_active_day, total_income, extra_non_wage_cost, peak_extra_non_wage_cost, offpeak_extra_non_wage_cost, prod_hour_'food','mart','messenger','bike', gmv_'food','mart','messenger','bike', incentive]
Index: []

In [38]:
bkk_0924['incentive'].unique()

array([nan, 'Streak Hours', 'Daily Hours', 'Daily Orders'], dtype=object)

In [41]:
bkk_0924[bkk_0924['incentive'] == 'Streak Hours']

,date,region,zone,driver_id,rider_level,most_freq_district,phone,driver_tier,dedicated_zones,total_online_hour,peak_online_hour,offpeak_online_hour,total_assign_hour,active_day,auto_assigned,auto_assigned_food,auto_assigned_mart,auto_assigned_messenger,auto_assigned_bike,auto_assigned_accepted,auto_assigned_accepted_food,auto_assigned_accepted_mart,auto_assigned_accepted_messenger,auto_assigned_accepted_bike,completed,completed_peak,completed_offpeak,completed_food,completed_mart,completed_messenger,completed_bike,cancelled_free,cancelled_free_food,cancelled_free_mart,cancelled_free_messenger,cancelled_free_bike,cancelled_not_free,cancelled_not_free_food,cancelled_not_free_mart,cancelled_not_free_messenger,cancelled_not_free_bike,driver_wage_food,driver_wage_mart,driver_wage_msg,driver_wage_bike,DELIVERY_FEE_DYNAMIC_ON_TOP,DELIVERY_FEE_DYNAMIC_ON_TOP_food,DELIVERY_FEE_DYNAMIC_ON_TOP_mart,DELIVERY_FEE_DYNAMIC_ON_TOP_msg,DELIVERY_FEE_DYNAMIC_ON_TOP_bike,"CONVERT_COIN_TO_CASH_'food','mart','messenger','bike'","guarantee_'food','mart','messenger','bike'","active_bonus_'food','mart','messenger','bike'","streak_'food','mart','messenger','bike'","period_'food','mart','messenger','bike'","daily_'food','mart','messenger','bike'","own_fleet_wage_'food','mart','messenger','bike'","own_fleet_incentive_'food','mart','messenger','bike'","CONVERT_VAULT_COINS_TO_CASH_'food','mart','messenger','bike'","main_peak_hour_weekly_other_emg_incentive_no_id_'food','mart','messenger','bike'",tier_productivity_incentive,active_driver,active_driver_peak,active_driver_offpeak,aa_completed,zone_online_day,region_online_day,region_active_day,total_income,extra_non_wage_cost,peak_extra_non_wage_cost,offpeak_extra_non_wage_cost,"prod_hour_'food','mart','messenger','bike'","gmv_'food','mart','messenger','bike'",incentive
6,2025-09-24,BKK,BKK - Lose,LMDDMQYTA,5,N,645951087,LEGEND,BKK_LOSE_SWING_EXPERIMENT,1.7906,0.8334,0.9572,1.195930,1,3,3,0,0,0,2,2,0,0,0,2,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,87.68,NaN,NaN,NaN,13.0,13.0,NaN,NaN,NaN,0.000000,0.0,15.277778,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,115.957778,15.277778,0.0,0.0,0.0,449.00,Streak Hours
16,2025-09-26,BKK,BKK - Lose,LMDDMQYTA,5,N,645951087,LEGEND,BKK_LOSE_SWING_EXPERIMENT,1.8267,0.3334,1.4934,1.298062,1,6,6,0,0,0,5,5,0,0,0,5,4,1,5,0,0,0,0,0,0,0,0,0,0,0,0,0,156.19,NaN,NaN,NaN,35.0,35.0,NaN,NaN,NaN,13.558140,0.0,22.916667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,227.664806,22.916667,0.0,0.0,0.0,603.04,Streak Hours
22,2025-09-26,BKK,BKK - Swing,LMDYVFQ4I,4,N,961317107,GOLD,BKK_LOSE_SWING_EXPERIMENT,4.6932,1.3818,3.3114,2.554111,1,10,10,0,0,0,10,10,0,0,0,10,4,6,10,0,0,0,0,0,0,0,0,0,0,0,0,0,237.90,NaN,NaN,NaN,60.0,60.0,NaN,NaN,NaN,0.000000,0.0,90.163934,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,388.063934,90.163934,0.0,0.0,0.0,1767.00,Streak Hours
36,2025-09-25,BKK,BKK - Lose,LMDYVFQ4I,4,N,961317107,GOLD,BKK_LOSE_SWING_EXPERIMENT,5.4477,3.0027,2.4450,2.662729,1,12,12,0,0,0,9,9,0,0,0,9,2,7,9,0,0,0,0,0,0,0,0,0,0,0,0,0,235.77,NaN,NaN,NaN,39.0,39.0,NaN,NaN,NaN,0.000000,0.0,81.147541,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,355.917541,81.147541,0.0,0.0,0.0,1637.00,Streak Hours
54,2025-09-26,BKK,BKK - Lose,LMDFPJ3BY,9,N,616632945,LEGEND,BKK_LOSE_SWING_EXPERIMENT,5.2201,1.5000,3.7201,5.193330,1,13,11,2,0,0,13,11,2,0,0,13,0,13,11,2,0,0,0,0,0,0,0,0,0,0,0,0,338.20,61.19,NaN,NaN,37.0,37.0,0.0,NaN,NaN,32.252964,0.0,125.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,0,1,13,1.0,1.0,1,593.642964,125.000000,0.0,0.0,0.0,2219.44,Streak Hours
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5863,2025-09-26,BKK,BKK - Swing,LMDK5ZSKI,6,N,829986915,BRONZE,BKK_LOSE_SWING_EXPERIMENT,7.8086,2.9604,4.8481,6.648983,1,33,32,1,0,0,27,26,1,0,0,27,6,21,26,1,0,0,0,0,0,0,0,0,0,0,0,0,692.62,23.67,NaN,NaN,43.0,43.0,0.0,NaN,NaN,0.000000,0.0,161.413043,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,920.703043,161.413043,0.0,0.0,0.0,7449.85,Streak Hours
5870,2025-09-25,BKK,BKK - Swing,LMDK5ZSKI,6,N,829986915,BRONZE,BKK_LOSE_SWING_EXPERIMENT,9.0049,4.4649,4.5399,7.305593,1,42,42,0,0,0,37,37,0,0,0,36,16,20,36,0,0,0,0,0,0,0,0,0,0,0,0,0,979.47,NaN,NaN,NaN,90.0,90.0,NaN,NaN,NaN,50.000000,0.0,215.217391,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,1334.687391,215.217391,0.0,0.0,0.0,6330.09,Streak Hours
5884,2025-09-26,BKK,BKK - Lose,LMDK5ZSKI,6,N,829986915,BRONZE,BKK_LOSE_SWING_EXPERIMENT,0.4302,NaN,0.4302,0.180643,1,1,1,0,0,0,1,1,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,43.87,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,0.000000,0.0,5.978261,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,0,1,0,1.0,1.0,1,52.848261,5.978261,NaN,0.0,0.0,102.00,Streak Hours
5889,2025-09-24,BKK,BKK - Swing,LMDK5ZSKI,6,N,829986915,BRONZE,BKK_LOSE_SWING_EXPERIMENT,7.5733,3.3555,4.2177,6.079410,1,31,30,1,0,0,27,26,1,0,0,27,13,14,26,1,0,0,0,0,0,0,0,0,0,0,0,0,766.93,33.00,NaN,NaN,41.0,41.0,0.0,NaN,NaN,0.000000,0.0,161.413043,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,1,1,0,1.0,1.0,1,1002.343043,161.413043,0.0,0.0,0.0,4576.10,Streak Hours
5910,2025-09-24,BKK,BKK - Lose,LMDK5ZSKI,6,N,829986915,BRONZE,BKK_LOSE_SWING_EXPERIMENT,0.5348,NaN,0.5348,0.330139,1,4,4,0,0,0,2,2,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,28.96,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,0.000000,0.0,5.978261,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,0,1,0,1.0,1.0,1,37.938261,5.978261,NaN,0.0,0.0,129.00,Streak Hours

In [43]:
bkk_1001 = pd.read_csv('../bkk_with_incentives/bkk-1001.csv')

In [50]:
bkk_1004 = pd.read_csv('../bkk_with_incentives/bkk-1004-1007.csv')

In [52]:
bkk_1004['incentive'].unique()

array([nan, 'Streak Hours', 'Daily Hours', 'Daily Orders'], dtype=object)

In [ ]:
bkk_1001['incentive'].unique()

array([nan])

In [48]:
bkk_1001

,region,driver_id,assign_created_at,restaurant_name,restaurant_category,order_id,is_driver_accept,wage,on_top_fare,basket_size,drop_off_distance,distance_rider_to_restaurant,placed_to_match_second,rider_matched_to_arrived_restaurant_second,rider_waiting_time_in_restaurant_second,delivery_time_to_user_second,total_user_waiting_time_second,order_status,incentive
0,BKK,LMD0001LS,2025-10-01 10:52:45.269,ข้าวหมูแดงสีมรกต ซ.สุกร1 (Si Morakot The Origi...,Rice Dish,LMF-251001-719310178,False,39.54,4.0,876.0,5434.0,1022.8,2788,843,5,1069,4705,COMPLETED,NaN
1,BKK,LMD0001LS,2025-10-01 13:03:34.262,ก๋วยเตี๋ยวลูกชิ้นปลานายง้ำ (Mr. Ngam Fish Balls),Noodles,LMF-251001-032654943,False,36.45,8.0,385.0,6730.0,152.7,1232,1077,1300,735,4344,COMPLETED,NaN
2,BKK,LMD0001LS,2025-10-01 13:11:53.963,ร้านข้าวแกงบางลำพู2517 (Bang Lamphu Curry Rice...,Thai,LMF-251001-067886501,False,28.91,8.0,196.0,3956.0,2037.3,745,966,245,1135,3091,COMPLETED,NaN
3,BKK,LMD0001LS,2025-10-01 13:17:41.314,โหวเส่กหมิ่น - Ho Sek Min แฟลตสวนกวางตุ้ง,Noodles,LMF-251001-210171442,False,71.85,8.0,173.0,10491.0,751.7,0,0,0,0,0,EXPIRED,NaN
4,BKK,LMD006HF1,2025-10-01 18:24:18.993,KAWNA ข้าวหน้า รามคำแหง 129 สาขารามคำแหง 129 O...,Rice Dish,LMF-251001-043851056,False,41.71,2.0,343.0,8114.0,3314.2,1917,861,968,726,4472,COMPLETED,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392206,BKK,LMDZZTU1N,2025-10-01 15:41:09.262,Shinkanzen Sushi (ชินคันเซ็น ซูชิ) ซีคอน บางแค,Japanese,LMF-251001-626497456,True,30.00,0.0,170.0,2573.0,1809.4,59,449,429,639,1576,COMPLETED,NaN
392207,BKK,LMDZZTU1N,2025-10-01 16:04:55.655,กรีกโยเกิร์ต by miimiim (Greek Yogurt by Miimi...,Dessert,LMF-251001-647057278,True,20.40,0.0,378.0,2310.0,76.0,484,77,536,381,1478,COMPLETED,NaN
392208,BKK,LMDZZTU1N,2025-10-01 16:09:48.420,จงรักผัดไทย (Jong Rak Padthai) จงรักผัดไทย (Jo...,Thai,LMF-251001-785862757,True,20.40,0.0,119.0,1379.0,1959.4,227,553,446,8,1234,COMPLETED,NaN
392209,BKK,LMDZZTU1N,2025-10-01 16:11:32.728,กรีกโยเกิร์ต by miimiim (Greek Yogurt by Miimi...,Dessert,LMF-251001-099972211,True,20.40,0.0,189.0,2391.0,0.0,87,77,935,8,1107,COMPLETED,NaN
392210,BKK,LMDZZTU1N,2025-10-01 16:31:00.139,นู๋นุ๊ก ข้าวต้มกุ๊ย (Nunook Rice Porridge) M09...,Late Night Rice Porridge,LMF-251001-566840012,True,56.85,0.0,190.0,8955.0,1562.7,30,488,9,1196,1723,COMPLETED,NaN

In [46]:
bkk_1014 = pd.read_csv('../bkk_with_incentives/bkk-1014.csv')

In [47]:
bkk_1014['incentive'].unique()

array([nan])